In [5]:
from google.cloud import bigquery
import os

def init_bigquery_client() -> bigquery.Client:
    """Initialize BigQuery client"""
    bq_credentials_path = os.getenv('GOOGLE_APPLICATION_CREDENTIALS')
    project_id = os.getenv('GCP_PROJECT_ID')
    
    if not project_id:
        raise ValueError("GCP_PROJECT_ID environment variable not set")
    
    if bq_credentials_path and os.path.exists(bq_credentials_path):
        os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = bq_credentials_path
        print(f"Using BigQuery credentials: {bq_credentials_path}")
    
    return bigquery.Client(project=project_id)

#pulling data from bigquery tables
nodes_query = "SELECT * FROM `etl-testing-478716.instagram_graph.nodes`"
edges_query = "SELECT * FROM `etl-testing-478716.instagram_graph.edges`"
client = init_bigquery_client()
nodes_bq = client.query(nodes_query).to_dataframe()
edges_bq = client.query(edges_query).to_dataframe()

Using BigQuery credentials: etl-testing-478716-c0b6c2c512e0.json

/opt/miniconda3/envs/heyyall/lib/python3.13/site-packages/google/cloud/bigquery/table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

In [28]:
#deduplicating nodes based on username and full_name
nodes_dedup = nodes_bq.drop_duplicates(subset = ["username", "full_name"])

#filter to public accounts only
nodes_dedup_public = nodes_dedup[nodes_dedup['is_private'] == False].reset_index(drop=True)

#getting lockett followers
lockett_followers_list = edges_bq[edges_bq['target'] == 'locketfuxx']['source'].unique().tolist()

nodes_dedup_public['is_lockett_follower'] = nodes_dedup_public['username'].apply(lambda x: x in lockett_followers_list)

nodes_locket_follower = nodes_dedup_public[nodes_dedup_public['is_lockett_follower'] == True].reset_index(drop=True)

In [6]:
#deduplicating nodes based on username and full_name
nodes_dedup = nodes_bq.drop_duplicates(subset = ["username", "full_name"])

#filter to public accounts only
nodes_dedup_public = nodes_dedup[nodes_dedup['is_private'] == False].reset_index(drop=True)
#split into two df's based on is_verified
nodes_verified = nodes_dedup_public[nodes_dedup_public['is_verified'] == True].reset_index(drop=True)
nodes_unverified = nodes_dedup_public[nodes_dedup_public['is_verified'] == False].reset_index(drop=True)

print(f"Total nodes: {len(nodes_dedup)}")
print(f"Verified nodes: {len(nodes_verified)}")
print(f"Unverified nodes: {len(nodes_unverified)}")

Total nodes: 5290
Verified nodes: 542
Unverified nodes: 2810

In [29]:
from apify_client import ApifyClient
from main import run_profile_crawl

In [30]:
import time
import pandas as pd

In [31]:
print("Running the next step...")
username_list = nodes_locket_follower['username'].tolist()
print(f"Total usernames to crawl: {len(username_list)}")

Running the next step...
Total usernames to crawl: 1546

In [33]:
profiles = run_profile_crawl(username_list)

#writing profiles to parquet file
run_id = str(int(time.time()))
profiles_df = pd.DataFrame(profiles)
profiles_df.to_parquet(f"profiles_{run_id}.parquet", index=False)

Crawling profiles for 1546 accounts...

[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> Status: RUNNING, Message:
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:50:27.030Z ACTOR: Pulling container image of build AIf7xvwjg39uyRUcq from registry.
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:50:27.032Z ACTOR: Creating container.
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:50:27.082Z ACTOR: Starting container.
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:50:27.083Z ACTOR: Running under "LIMITED_PERMISSIONS" permission level.
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:50:27.621Z INFO  System info {"apifyVersion":"3.6.0","apifyClientVersion":"2.22.2","crawleeVersion":"3.16.0","osType":"Linux","nodeVersion":"v22.22.1"}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:50:27.745Z INFO  Results Limit [object Object], ACTOR_MAX_PAID_DATASET_ITEMS
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> Status: RUNNING, Message: Starting the scraper with 1546 direct URL(s)
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:50:27.823Z INFO  [Status message]: Starting the scraper with 1546 direct URL(s)
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> Status: RUNNING, Message: Starting the crawler.
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:50:28.761Z INFO  CheerioCrawler: Starting the crawler.
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:50:34.084Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> Status: RUNNING, Message: Crawled 42/1546 pages, 0 failed requests, desired concurrency 52.
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> Status: RUNNING, Message: Crawled 104/1546 pages, 0 failed requests, desired concurrency 55.
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:50:34.086Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"2dkfRUnnjzAuXMg","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=jaysee","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:50:51.026Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. The proxy server rejected the request with status code 590 (UPSTREAM502)
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:50:51.028Z     at ClientRequest.<anonymous> (file:///usr/src/app/dist/984.index.js:16244:109) {"id":"yiR7Q0UjdZhpjC3","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=theanswersatx","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:50:52.426Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:50:52.428Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"xEigEXCZyhswonD","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=lericmon","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:50:56.013Z INFO  Restricted profile https://www.instagram.com/tinyspecksatx resolved with ID 61571689538
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> Status: RUNNING, Message: Crawled 150/1546 pages, 0 failed requests, desired concurrency 55.
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:50:58.960Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. request timed out after 30 seconds. {"id":"QLorKWC8ft4rCYK","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=antonetael","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:50:59.429Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Client network socket disconnected before secure TLS connection was established
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:50:59.430Z     at ClientRequest.<anonymous> (file:///usr/src/app/dist/984.index.js:16244:109) {"id":"JMwort2h7NrJlcn","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=jesuisamb","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:01.117Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:01.118Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"U3VKKmPKxof8Kd2","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=lanoon333","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:06.230Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. The proxy server rejected the request with status code 590 (UPSTREAM502)
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:06.232Z     at ClientRequest.<anonymous> (file:///usr/src/app/dist/984.index.js:16244:109) {"id":"xUuwjPW9PWTTXXd","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=officialgabrielamusic","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:06.816Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. The proxy server rejected the request with status code 590 (UPSTREAM503)
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:06.817Z     at ClientRequest.<anonymous> (file:///usr/src/app/dist/984.index.js:16244:109) {"id":"SKk88iRmBa7oWa6","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=egauxsells","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:07.825Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:07.826Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"T0eASZIjxzvUQjI","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=adesuwavia","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:09.116Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. 4852440CED790000:error:0A000119:SSL routines:tls_get_more_records:decryption failed or bad record mac:../deps/openssl/openssl/ssl/record/methods/tls_common.c:868:
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:09.117Z
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> Status: RUNNING, Message: Crawled 200/1546 pages, 0 failed requests, desired concurrency 52.
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:09.118Z     at ClientRequest.<anonymous> (file:///usr/src/app/dist/984.index.js:16244:109) {"id":"DTYW2yRVVJnys5Y","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=mortalmajorityy","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:17.043Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:17.047Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"0FhE13a7cVIfiyV","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=vonbandatx","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:17.816Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. 4852440CED790000:error:0A000119:SSL routines:tls_get_more_records:decryption failed or bad record mac:../deps/openssl/openssl/ssl/record/methods/tls_common.c:868:
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:17.817Z
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:17.818Z     at ClientRequest.<anonymous> (file:///usr/src/app/dist/984.index.js:16244:109) {"id":"QkVzNlkNDjCn55Z","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=esme.moreno_","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> Status: RUNNING, Message: Crawled 271/1546 pages, 0 failed requests, desired concurrency 49.
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:19.122Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. request timed out after 30 seconds. {"id":"YRHNExC7plpshZx","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=rdxte","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:23.714Z INFO  Restricted profile https://www.instagram.com/directed.bydon resolved with ID 526065747
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:24.723Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. 4852440CED790000:error:0A000119:SSL routines:tls_get_more_records:decryption failed or bad record mac:../deps/openssl/openssl/ssl/record/methods/tls_common.c:868:
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:24.724Z
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:24.726Z     at ClientRequest.<anonymous> (file:///usr/src/app/dist/984.index.js:16244:109) {"id":"eKJI8fOGX1mMUgp","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=thedarlingjane","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:26.824Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:26.825Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"K7fzwZZzVSF6QsL","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=love.freq","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:26.914Z INFO  Restricted profile https://www.instagram.com/valeraartwork resolved with ID 2320675981
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:28.713Z INFO  Restricted profile https://www.instagram.com/liv.austincosmetictattoos resolved with ID 52702714275
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:28.817Z INFO  CheerioCrawler:Statistics: CheerioCrawler request statistics: {"requestAvgFailedDurationMillis":null,"requestAvgFinishedDurationMillis":5394,"requestsFinishedPerMinute":324,"requestsFailedPerMinute":0,"requestTotalDurationMillis":1774704,"requestsTotal":329,"crawlerRuntimeMillis":60988,"retryHistogram":[329]}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:29.019Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. 4852440CED790000:error:0A000410:SSL routines:ssl3_read_bytes:ssl/tls alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:918:SSL alert number 40
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:29.021Z
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:29.022Z     at ClientRequest.<anonymous> (file:///usr/src/app/dist/984.index.js:16244:109) {"id":"PTOvHp1o3Ix12Sp","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=directed.bydon","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:29.023Z INFO  CheerioCrawler:AutoscaledPool: state {"currentConcurrency":16,"desiredConcurrency":43,"systemStatus":{"isSystemIdle":false,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":0},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.6,"actualRatio":0.362},"cpuInfo":{"isOverloaded":true,"limitRatio":0.4,"actualRatio":0.532},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":0}}}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> Status: RUNNING, Message: Crawled 329/1546 pages, 0 failed requests, desired concurrency 46.
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:29.224Z INFO  Restricted profile https://www.instagram.com/helizaca resolved with ID 322847717
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:30.480Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. The proxy server rejected the request with status code 590 (UPSTREAM502)
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> Status: RUNNING, Message: Crawled 382/1546 pages, 0 failed requests, desired concurrency 43.
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:30.481Z     at ClientRequest.<anonymous> (file:///usr/src/app/dist/984.index.js:16244:109) {"id":"a5bSUy8SoG29sYk","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=smileyfacesonmars","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:44.827Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:44.828Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"koTwksUH8BO7xbI","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=theemaneaterr","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:45.550Z INFO  Restricted profile https://www.instagram.com/shambabbyy resolved with ID 6997686000
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:46.024Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. 4852440CED790000:error:0A000119:SSL routines:tls_get_more_records:decryption failed or bad record mac:../deps/openssl/openssl/ssl/record/methods/tls_common.c:868:
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:46.025Z
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> Status: RUNNING, Message: Crawled 450/1546 pages, 0 failed requests, desired concurrency 40.
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:46.026Z     at ClientRequest.<anonymous> (file:///usr/src/app/dist/984.index.js:16244:109) {"id":"nKLe9h3AAHLRFf1","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=dustisaa","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:51.119Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. The proxy server rejected the request with status code 590 (UPSTREAM503)
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:51.120Z     at ClientRequest.<anonymous> (file:///usr/src/app/dist/984.index.js:16244:109) {"id":"k7CY0nKQ1qMCVwi","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=marcrene_b","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:51.616Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> Status: RUNNING, Message: Crawled 510/1546 pages, 0 failed requests, desired concurrency 40.
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:51:51.617Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"XgZ8DCwT6DAR084","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=watermegansugar","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:52:00.565Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:52:00.566Z     at CheerioCrawler._requestFunctionErrorHandler (file:///usr/src/app/dist/index.js:1:28024) {"id":"MSm8QnqKwgGhMbP","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=itza.xox","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:52:01.725Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Client network socket disconnected before secure TLS connection was established
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:52:01.726Z     at ClientRequest.<anonymous> (file:///usr/src/app/dist/984.index.js:16244:109) {"id":"SWVlruGdnllowLe","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=heccorg","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:52:03.116Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. request timed out after 30 seconds. {"id":"1cJho17Bxq9DZH5","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=forgotaboutdra","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> Status: RUNNING, Message: Crawled 562/1546 pages, 0 failed requests, desired concurrency 40.
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:52:03.418Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. request timed out after 30 seconds. {"id":"W3zWMltLArqdR6U","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=withallmyh34rt","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:52:12.029Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. request timed out after 30 seconds. {"id":"EwSbRYqSR8IrbLR","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=avamorales44","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:52:12.125Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. request timed out after 30 seconds. {"id":"YWjpw44NRYpcEju","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=wholiuhhh","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:52:14.726Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. The HTTP/2 stream has been early terminated
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:52:14.728Z     at ClientRequest.<anonymous> (file:///usr/src/app/dist/984.index.js:16244:109) {"id":"6Y8rbutLJRbIler","url":"https://i.instagram.com/api/v1/users/web_profile_info/?username=zenith_is.unreachable","retryCount":1}
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> 2026-03-31T20:52:16.722Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Request blocked, retrying it again with different session
[apify.instagram-profile-scraper runId:dLG6Gb6png5yqUFHt] -> Status: RUNNING, Message: Crawled 637/1546 pages, 0 failed requests, desired concurrency 42.

Fetched profiles for 1546 accounts

In [ ]:

# Turning profiles into dataframe and saving as parquet file
profiles_df['Ratio'] = profiles_df['followersCount'] / profiles_df['followsCount'].replace(0, 1)  # Avoid division by zero
# run_id = str(int(time.time()))
# profiles_df.to_parquet(f"profiles_{run_id}.parquet", index=False)
# print(f"Saved profiles with ratio as parquet file locally")

print("Top 20 profiles by ratio and total followers:")
top_profiles = profiles_df.sort_values(by=["Ratio", "followersCount"], ascending=False).head(20)

Top 20 profiles by ratio and total followers:
                    username  followersCount  followsCount       Ratio  \
298              raicestexas        148685.0         530.0  280.537736
288                 zelladay        166025.0        1841.0   90.181966
448              thetessalee         55773.0         760.0   73.385526
1501               sad.jazzy         29695.0         433.0   68.579677
673               redrumclub         53070.0         832.0   63.786058
1263                 kgsratx         27030.0         437.0   61.853547
1328         almondmilkhunni        119152.0        2107.0   56.550546
891              maysterling         35430.0         694.0   51.051873
141         _mechellenicole_         70746.0        1473.0   48.028513
1267               imtomfurd         64143.0        1559.0   41.143682
496            kingdomaustin         29968.0         847.0   35.381346
131          verylonely.shop         24166.0         753.0   32.092961
898                glazezine          6400.0         202.0   31.683168
658              pizzo.pedro         22984.0         739.0   31.101488
280               levitation        102299.0        3429.0   29.833479
315   communitygarden.austin         13610.0         470.0   28.957447
1442             bambina___0         29496.0        1061.0   27.800189
1355       thevelvetdaydream         33719.0        1216.0   27.729441
1280           grocerybag.tx          8697.0         327.0   26.596330
884            beeblackwell_          7294.0         280.0   26.050000

     isBusinessAccount private         businessCategoryName
298               True   False  None,Nonprofit organization
288               True   False                  None,Artist
448              False   False                        Model
1501              True   False                  None,Artist
673               True   False           None,Musician/band
1263             False   False                         None
1328             False   False                Musician/band
891              False   False                         None
141              False   False                Health/beauty
1267             False   False                         None
496              False   False           Dance & Night Club
131              False   False                         None
898               True   False                None,Magazine
658              False   False              Digital creator
280               True   False                   None,Event
315               True   False                         None
1442             False   False                         None
1355             False   False                         Band
1280              True   False                         None
884              False   False                         None

In [48]:

keep_cols = ['inputUrl', 'id', 'username', 'url', 'fullName', 'biography',
       'externalUrls', 'followersCount', 'followsCount', 'hasChannel',
       'highlightReelCount', 'isBusinessAccount', 'joinedRecently',
       'businessCategoryName', 'private', 'verified', 'profilePicUrl',
       'profilePicUrlHD', 'igtvVideoCount', 'relatedProfiles',
       'latestIgtvVideos', 'postsCount', 'latestPosts', 'fbid', 'externalUrl',
       'externalUrlShimmed','Ratio']

profiles_df = profiles_df[keep_cols]

# repeated columns 
for col in ["externalUrls", "relatedProfiles", "latestIgtvVideos", "latestPosts"]:
    if col in profiles_df.columns:
        profiles_df[col] = profiles_df[col].apply(lambda x: x if isinstance(x, list) else [])
        
#creating profile table with username, followersCount, followsCount, and Ratio
from main import BQ_DATASET, GCP_PROJECT

bq = init_bigquery_client()
    
# Create dataset if it doesn't exist
dataset_id = f"{GCP_PROJECT}.{BQ_DATASET}"
dataset = bigquery.Dataset(dataset_id)
dataset.location = "US"
bq.create_dataset(dataset, exists_ok=True)
print(f"Dataset {BQ_DATASET} ready")

# Define nodes table schema
profiles_schema = [
    bigquery.SchemaField("inputUrl", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("id", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("username", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("url", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("fullName", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("biography", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("externalUrls", "STRING", mode="REPEATED"),
    bigquery.SchemaField("followersCount", "INTEGER", mode="NULLABLE"),
    bigquery.SchemaField("followsCount", "INTEGER", mode="NULLABLE"),
    bigquery.SchemaField("hasChannel", "BOOLEAN", mode="NULLABLE"),
    bigquery.SchemaField("highlightReelCount", "INTEGER", mode="NULLABLE"),
    bigquery.SchemaField("isBusinessAccount", "BOOLEAN", mode="NULLABLE"),
    bigquery.SchemaField("joinedRecently", "BOOLEAN", mode="NULLABLE"),
    bigquery.SchemaField("businessCategoryName", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("private", "BOOLEAN", mode="NULLABLE"),
    bigquery.SchemaField("verified", "BOOLEAN", mode="NULLABLE"),
    bigquery.SchemaField("profilePicUrl", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("profilePicUrlHD", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("igtvVideoCount", "INTEGER", mode="NULLABLE"),
    bigquery.SchemaField("relatedProfiles", "STRING", mode="REPEATED"),
    bigquery.SchemaField("latestIgtvVideos", "STRING", mode="REPEATED"),
    bigquery.SchemaField("postsCount", "INTEGER", mode="NULLABLE"),
    bigquery.SchemaField("latestPosts", "STRING", mode="REPEATED"),
    bigquery.SchemaField("fbid", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("externalUrl", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("externalUrlShimmed", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("Ratio", "FLOAT", mode="NULLABLE"),
]


def ensure_required_columns(df: pd.DataFrame, schema_function) -> pd.DataFrame:
    """
    Ensure all required columns exist in DataFrame based on BigQuery schema definition.
    
    Args:
        df: Input DataFrame
        schema_function: Function that returns BigQuery schema (e.g., define_schema_users)
    
    Returns:
        DataFrame with all required columns from schema
    """
    # Get schema from the schema function
    schema = schema_function()
    
    # Extract column names and types from schema
    for field in schema:
        col_name = field.name
        field_type = field.field_type
        
        if col_name not in df.columns:
            # Set appropriate defaults based on BigQuery field type
            if field_type == 'BOOLEAN':
                df[col_name] = False
            elif field_type in ['INTEGER', 'FLOAT', 'NUMERIC']:
                df[col_name] = None
            elif field_type in ['TIMESTAMP', 'DATETIME', 'DATE']:
                df[col_name] = None
            else:  # STRING and other types
                df[col_name] = None
    
    # Fill NaN values for boolean columns
    boolean_fields = [field.name for field in schema if field.field_type == 'BOOLEAN']
    for col in boolean_fields:
        if col in df.columns:
            df.loc[:, col] = df[col].fillna(False)
    
    # Return DataFrame with only schema columns in the right order
    schema_columns = [field.name for field in schema]
    available_columns = [col for col in schema_columns if col in df.columns]
    
    # Create a clean copy with reset index to avoid PyArrow conversion issues
    result_df = df[available_columns].copy()
    result_df.reset_index(drop=True, inplace=True)

    # Ensure repeated fields are lists of strings
    repeated_fields = ["externalUrls", "relatedProfiles", "latestIgtvVideos", "latestPosts"]
    for col in repeated_fields:
        if col in result_df.columns:
            result_df[col] = result_df[col].apply(
                lambda x: [str(i) for i in x] if isinstance(x, list) else ([] if pd.isna(x) or x is None else [str(x)])
            )
    
    return result_df

# Ensure all required columns exist in profiles_df based on profiles_schema
profiles_df = ensure_required_columns(profiles_df, lambda: profiles_schema)

/var/folders/d6/wbxdxj_s71ngq7ft6m6_6krc0000gn/T/ipykernel_18182/1272207864.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  profiles_df[col] = profiles_df[col].apply(lambda x: x if isinstance(x, list) else [])

Using BigQuery credentials: etl-testing-478716-c0b6c2c512e0.json
Dataset instagram_graph ready

/var/folders/d6/wbxdxj_s71ngq7ft6m6_6krc0000gn/T/ipykernel_18182/1272207864.py:94: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.loc[:, col] = df[col].fillna(False)

In [49]:


# Create profiles table if it doesn't exist
profiles_table = bigquery.Table(f"{dataset_id}.profiles", schema=profiles_schema)
bq.create_table(profiles_table, exists_ok=True)

# Insert profiles data into BigQuery
job_config = bigquery.LoadJobConfig(
    schema=profiles_schema,
    write_disposition=bigquery.WriteDisposition.WRITE_TRUNCATE,
)
load_job = bq.load_table_from_dataframe(profiles_df, f"{dataset_id}.profiles", job_config=job_config)
load_job.result()  # Wait for the job to complete
print(f"Inserted {len(profiles_df)} profiles into {dataset_id}.profiles")

/opt/miniconda3/envs/heyyall/lib/python3.13/site-packages/google/cloud/bigquery/_pandas_helpers.py:484: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

Inserted 1546 profiles into etl-testing-478716.instagram_graph.profiles

In [37]:

top_profiles[["username", "followersCount", "followsCount", "Ratio", "isBusinessAccount", "private", "businessCategoryName"]]

,username,followersCount,followsCount,Ratio,isBusinessAccount,private,businessCategoryName
298,raicestexas,148685.0,530.0,280.537736,True,False,"None,Nonprofit organization"
288,zelladay,166025.0,1841.0,90.181966,True,False,"None,Artist"
448,thetessalee,55773.0,760.0,73.385526,False,False,Model
1501,sad.jazzy,29695.0,433.0,68.579677,True,False,"None,Artist"
673,redrumclub,53070.0,832.0,63.786058,True,False,"None,Musician/band"
1263,kgsratx,27030.0,437.0,61.853547,False,False,None
1328,almondmilkhunni,119152.0,2107.0,56.550546,False,False,Musician/band
891,maysterling,35430.0,694.0,51.051873,False,False,None
141,_mechellenicole_,70746.0,1473.0,48.028513,False,False,Health/beauty
1267,imtomfurd,64143.0,1559.0,41.143682,False,False,None
496,kingdomaustin,29968.0,847.0,35.381346,False,False,Dance & Night Club
131,verylonely.shop,24166.0,753.0,32.092961,False,False,None
898,glazezine,6400.0,202.0,31.683168,True,False,"None,Magazine"
658,pizzo.pedro,22984.0,739.0,31.101488,False,False,Digital creator
280,levitation,102299.0,3429.0,29.833479,True,False,"None,Event"
315,communitygarden.austin,13610.0,470.0,28.957447,True,False,None
1442,bambina___0,29496.0,1061.0,27.800189,False,False,None
1355,thevelvetdaydream,33719.0,1216.0,27.729441,False,False,Band
1280,grocerybag.tx,8697.0,327.0,26.596330,True,False,None
884,beeblackwell_,7294.0,280.0,26.050000,False,False,None

In [39]:
top_profiles['followersCount'].sum() / 1000

np.float64(1048.382)

In [ ]:
#running crawl on selected accounts 
from main import store_to_bigquery
from main import run_bfs_crawl

seed_accounts = []


run_id = str(int(time.time()))
G = run_bfs_crawl(seed_accounts)
#before storing save as parquet files and save locally as backup 
# Insert data
nodes = [{"username": n, **d} for n, d in G.nodes(data=True)]
edges = [{"source": u, "target": v, **d} for u, v, d in G.edges(data=True)]

# Save as parquet files locally
nodes_df = pd.DataFrame(nodes)
edges_df = pd.DataFrame(edges)
nodes_df.to_parquet(f"nodes_{run_id}.parquet", index=False)
edges_df.to_parquet(f"edges_{run_id}.parquet", index=False)
print(f"Saved nodes and edges as parquet files locally")

#saving to biquery dataset
store_to_bigquery(G)

In [18]:
#visualizing network 
import networkx as nx

G = nx.DiGraph()  # Directed graph for following relationships
# Add nodes and edges to G based on your data

nodes_bq = nodes_bq.drop_duplicates(subset=['username']).reset_index(drop=True)
edges_bq = edges_bq.drop_duplicates(subset=['source', 'target']).reset_index(drop=True)

for item,row in nodes_bq.iterrows():
    G.add_node(row['username'], is_verified=row['is_verified'], is_private=row['is_private'])

for item,row in edges_bq.iterrows():
    G.add_edge(row['source'], row['target'], **row.to_dict())
import pandas as pd

# Replace pd.NA and None with empty string for all node attributes
for n, d in G.nodes(data=True):
    for k, v in list(d.items()):
        if v is pd.NA or v is None:
            d[k] = ""

# Replace pd.NA and None with empty string for all edge attributes
for u, v, d in G.edges(data=True):
    for k, v2 in list(d.items()):
        if v2 is pd.NA or v2 is None:
            d[k] = ""

nx.write_gexf(G, "my_graph.gexf")

In [60]:
#using skip trace apify api 

from crawler import APIFY_TOKEN



def fetch_skip_trace(input_params: dict) -> list[dict]:
    """
    For each name, phone number, or email, fetch associated Instagram accounts using Skip Trace API.
    At least one of name, phone_number, or email must be provided.
    """
    # if not (input_params.get("name") or input_params.get("phone_number") or input_params.get("email")):
    #     raise ValueError("At least one of name, phone_number, or email must be provided.")
    
    POSH_TRACE = 'hypebridge/posh-vip'
    apify = ApifyClient(APIFY_TOKEN)

    run = apify.actor(POSH_TRACE).call(run_input=input_params)
    return list(apify.dataset(run["defaultDatasetId"]).iterate_items())

In [86]:
test_posh = {"startUrls": [
    {"url": "https://posh.vip/explore?when=This+Month&sort=Largest&location=%7B%22type%22%3A%22custom%22%2C%22location%22%3A%22Austin%2C+TX%2C+USA%22%2C%22long%22%3A-97.7430608%2C%22lat%22%3A30.267153%7D"}
],
"maxEvents": 500,
"scrapeEventDetails": True
}

big_results_df = fetch_skip_trace(test_posh)
#store as parquet file locally
run_id = str(int(time.time()))
big_results_df = pd.DataFrame(big_results_df)
big_results_df.to_parquet(f"posh_results_{run_id}.parquet", index=False)
print(f"Saved Posh results as parquet file locally")

[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> Status: RUNNING, Message:
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:22.998Z ACTOR: Pulling container image of build VGlEYq35ZQlbL044v from registry.
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:24.137Z ACTOR: Creating container.
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:24.188Z ACTOR: Starting container.
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:24.189Z ACTOR: Running under "LIMITED_PERMISSIONS" permission level.
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:26.589Z INFO  System info {"apifyVersion":"3.5.2","apifyClientVersion":"2.21.0","crawleeVersion":"3.15.3","osType":"Linux","nodeVersion":"v20.19.6"}
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:26.678Z INFO  Starting Posh.vip scraper {"startUrlCount":1,"scrapeEventDetails":true,"maxEvents":500}
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:26.680Z INFO  Detected deeplink for: Austin, TX, USA (This Month)
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:26.926Z INFO  CheerioCrawler: Starting the crawler.
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:27.569Z INFO  Processing deeplink search: Austin, TX, USA (This Month)
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> Status: RUNNING, Message: Starting the crawler.
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:27.570Z INFO  Fetching events from deeplink: Austin, TX, USA (This Month)
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:30.564Z INFO  Found 200 events from deeplink search
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:30.569Z INFO  Found 200 events from deeplink
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> Status: RUNNING, Message: Crawled 0/200 pages, 0 failed requests, desired concurrency 10.
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:37.291Z INFO  Enqueued 200 events for detailed scraping
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:38.393Z INFO  Scraping detailed event: sunset-party-w-moon-boots-crg
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:38.591Z INFO  Scraping detailed event: pretty-icy-1
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:38.693Z INFO  Scraping detailed event: y2knightatmalavida
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:38.699Z INFO  Scraping detailed event: love-more-rnb-april-19-austin-texas
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:38.791Z INFO  Scraping detailed event: sunday-funday-for-my-birthday-hoessss
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:38.992Z INFO  Scraping detailed event: ilov3rb-w-mariah-the-scientist
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:39.191Z INFO  Scraping detailed event: sunset-sessions-atx-5
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:39.396Z INFO  Scraping detailed event: chris-and-jalen-party-boat-2026
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:39.790Z INFO  Scraping detailed event: otc-springfest-2026
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:39.791Z INFO  Detailed event scraped: Sunset Party w/ MOON BOOTS + CRG!
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:39.792Z INFO  Progress: 1 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:39.794Z INFO  Detailed event scraped: Y2K 2000S PARTY AT MALA VIDA
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:39.794Z INFO  Progress: 2 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:39.795Z INFO  Detailed event scraped: Pretty Icy
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:39.795Z INFO  Progress: 3 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:39.796Z INFO  Detailed event scraped: Love More Rnb, April 19 , Austin Texas
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:39.796Z INFO  Progress: 4 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:39.797Z INFO  Detailed event scraped: Sunday Funday For My Birthday Hoessss
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:39.798Z INFO  Progress: 5 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:40.189Z INFO  Detailed event scraped: Chris And Jalen  Party  Boat 2026
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:40.190Z INFO  Progress: 6 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:40.293Z INFO  Scraping detailed event: mariah-the-scientist-concert-afterparty
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:40.514Z INFO  Detailed event scraped: OTC  SPRINGFEST 2026 *VICKEELO PERFORMING *
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:40.515Z INFO  Progress: 7 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:40.526Z INFO  Detailed event scraped: ILOV3R&B w/ Mariah The Scientist
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:40.527Z INFO  Progress: 8 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:40.536Z INFO  Detailed event scraped: Mariah The Scientist Concert AfterParty | Riviere
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:40.536Z INFO  Progress: 9 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:43.190Z INFO  Scraping detailed event: eat-the-rich-runway-show
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:43.290Z INFO  Scraping detailed event: sun-buns-chunky-bass
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:43.400Z INFO  Scraping detailed event: iyanias-24th-birthday-dinner-1
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:43.591Z INFO  Scraping detailed event: tribalera-y-botas
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:43.594Z INFO  Detailed event scraped: EAT THE RICH
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:43.595Z RUNWAY SHOW
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:43.595Z INFO  Progress: 10 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:43.695Z INFO  Scraping detailed event: aunties-house-let-the-good-times26
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:43.889Z INFO  Scraping detailed event: 4-all-beyonce-party
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:43.991Z INFO  Scraping detailed event: machine-after-dark-odumodublvck-live-performance
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:44.194Z INFO  Scraping detailed event: golden-hour-pilates-paddle
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:44.290Z INFO  Scraping detailed event: caf-con-ronthe-long-goodbye
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:44.294Z INFO  Detailed event scraped: Iyania’s 24th  Birthday Dinner
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:44.295Z INFO  Progress: 11 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:44.494Z INFO  Detailed event scraped: Sun, Buns & Chunky Bass
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:44.495Z INFO  Progress: 12 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:44.599Z INFO  Detailed event scraped: "4" All Beyonce Party
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:44.599Z INFO  Progress: 13 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:44.602Z INFO  Detailed event scraped: TRIBALERA Y BOTAS
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:44.602Z INFO  Progress: 14 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:44.690Z INFO  Detailed event scraped: Café con Ron@The Long Goodbye
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:44.691Z INFO  Progress: 15 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:44.692Z INFO  Detailed event scraped: GOLDEN HOUR PILATES & PADDLE
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:44.692Z INFO  Progress: 16 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:44.798Z INFO  Detailed event scraped: Auntie's House: Let the Good Times....'26
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:44.799Z INFO  Progress: 17 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:44.892Z INFO  Detailed event scraped: Machine After Dark - Odumodublvck Live Performance
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:44.893Z INFO  Progress: 18 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:44.996Z INFO  Scraping detailed event: los-dos-twins
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:44.999Z INFO  Scraping detailed event: nvtrium-and-friends-vol-ii
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:45.190Z INFO  Detailed event scraped: NVTRIUM AND FRIENDS VOL. II
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:45.191Z INFO  Progress: 19 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:45.203Z INFO  Scraping detailed event: sumn2say-open-mic-experience
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:45.213Z INFO  Detailed event scraped: LOS DOS @TWINS
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:45.214Z INFO  Progress: 20 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:45.413Z INFO  Detailed event scraped: SUMN2SAY: Open Mic Experience
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:45.413Z INFO  Progress: 21 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:45.726Z INFO  Scraping detailed event: flowers-friends-2
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:45.733Z INFO  Scraping detailed event: artist-talk-tending-lineage-closing-reception
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:45.830Z INFO  Detailed event scraped: Artist Talk: Tending Lineage Closing Reception
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:45.849Z INFO  Progress: 22 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:45.852Z INFO  Detailed event scraped: Flowers & Friends 2
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> Status: RUNNING, Message: Crawled 24/201 pages, 0 failed requests, desired concurrency 10.
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:45.853Z INFO  Progress: 23 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:48.890Z INFO  Scraping detailed event: taco-tuesday-422
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:48.996Z INFO  Scraping detailed event: elemental-earth
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:49.292Z INFO  Scraping detailed event: rooftop-rodeo-1
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:49.391Z INFO  Scraping detailed event: brent-faiyaz-bryson-tiller-night
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:49.499Z INFO  Scraping detailed event: 30-over-rave-throwbacks-club-classics
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:49.601Z INFO  Scraping detailed event: medicine-waves-sacred-oceans-at-the-honeycomb-dome
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:49.691Z INFO  Detailed event scraped: ELEMENTAL: EARTH
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:49.691Z INFO  Progress: 24 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:49.692Z INFO  Detailed event scraped: Tacos & Tequila Tuesday
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:49.692Z INFO  Progress: 25 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:49.790Z INFO  Scraping detailed event: daygaze-day-party-jos-tha-dj-official-birthday-celebration
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:49.899Z INFO  Scraping detailed event: builders-dreamers-3
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:49.992Z INFO  Detailed event scraped: Medicine Waves: Sacred Oceans at the Honeycomb Dome
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:50.015Z INFO  Progress: 26 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:50.019Z INFO  Detailed event scraped: BRENT FAIYAZ & BRYSON TILLER NIGHT
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:50.020Z INFO  Progress: 27 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:50.091Z INFO  Detailed event scraped: Daygaze Day Party: Jos Tha DJ Official Birthday Celebration
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:50.092Z INFO  Progress: 28 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:50.099Z INFO  Scraping detailed event: halfdays-austin-walk
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:50.294Z INFO  Detailed event scraped: 30 Over Rave: Throwbacks. Club classics.
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:50.294Z INFO  Progress: 29 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:50.489Z INFO  Detailed event scraped: Builders & Dreamers
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:50.490Z INFO  Progress: 30 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:50.492Z INFO  Detailed event scraped: Halfdays Austin Walk
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:50.493Z INFO  Progress: 31 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:50.505Z INFO  Scraping detailed event: clunis
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:50.592Z INFO  Detailed event scraped: ROOFTOP RODEO
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:50.593Z INFO  Progress: 32 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:50.789Z INFO  Scraping detailed event: hush-house-w-vidaurri-and-mikayla-desiree-0403-0404
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:50.792Z INFO  Detailed event scraped: Clunis
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:50.793Z INFO  Progress: 33 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:50.895Z INFO  Scraping detailed event: hush-house-w-crg-and-cid-at-the-one-0404-0405
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:51.005Z INFO  Scraping detailed event: april-3rd-black-smurf-live-in-austin-tx
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:51.107Z INFO  Scraping detailed event: jock-strap-night-austin-eagle-2026-4-3-7-0
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:51.289Z INFO  Detailed event scraped: Hush House w/ XTK and Keno 04.03 / 04.04
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:51.290Z INFO  Progress: 34 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:51.306Z INFO  Scraping detailed event: customize-a-sunhat-craft-mondays
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:51.307Z INFO  Scraping detailed event: pipecleaner-bouquet-craft-monday
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:51.392Z INFO  Scraping detailed event: hairbrush-painting-craft-mondays
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:51.399Z INFO  Detailed event scraped: APRIL 3rd: Black Smurf Live in Austin, TX with WIFIGAWD
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:51.400Z INFO  Progress: 35 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:51.589Z INFO  Scraping detailed event: social-media-content-photoshoot
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:51.691Z INFO  Detailed event scraped: Jock Strap Night @ Austin Eagle Powered By X-Spot
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:51.692Z INFO  Progress: 36 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:51.894Z INFO  Detailed event scraped: Customize A Sunhat - Craft Mondays
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:51.894Z INFO  Progress: 37 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:52.097Z INFO  Scraping detailed event: iyanias-24th-birthday-dinner
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:52.189Z INFO  Detailed event scraped: Pipecleaner Bouquet - Craft Mondays
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:52.189Z INFO  Progress: 38 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:52.220Z INFO  Detailed event scraped: Hairbrush Painting - Craft Mondays
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:52.221Z INFO  Progress: 39 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:52.225Z INFO  Detailed event scraped: Social Media Content Photoshoot
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:52.225Z INFO  Progress: 40 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:52.233Z INFO  Detailed event scraped: Iyania’s  24th  Birthday  Dinner
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:52.234Z INFO  Progress: 41 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:53.316Z INFO  Detailed event scraped: Sunset Sessions ATX
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:53.317Z INFO  Progress: 42 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:56.898Z INFO  Scraping detailed event: decoupage-wooden-eggs-craft-mondays
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:57.091Z INFO  Scraping detailed event: pint-night-the-pub-downtown-2026-4-3-1-0
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:57.095Z INFO  Scraping detailed event: pint-night-the-pub-downtown-2026-4-24-1-0
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:57.101Z INFO  Scraping detailed event: pint-night-the-pub-downtown-2026-5-1-1-0
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:57.195Z INFO  Scraping detailed event: pint-night-the-pub-downtown-2026-4-17-1-0
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:57.206Z INFO  Scraping detailed event: house4u-eterna-twins
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:57.295Z INFO  Scraping detailed event: jay-melodyz-toats-0417-1
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:57.391Z INFO  Scraping detailed event: aduro-film-presents-studio-access-pass
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:57.394Z INFO  Detailed event scraped: Decoupage Wooden Eggs - Craft Mondays
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:57.395Z INFO  Progress: 43 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:57.403Z INFO  Scraping detailed event: pint-night-the-pub-downtown-2026-4-10-1-0
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:57.408Z INFO  Detailed event scraped: Pint Night- The Pub Downtown
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:57.409Z INFO  Progress: 44 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:57.413Z INFO  Detailed event scraped: Pint Night- The Pub Downtown
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> Status: RUNNING, Message: Crawled 43/201 pages, 0 failed requests, desired concurrency 10.
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:57.414Z INFO  Progress: 45 events scraped
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:57.695Z INFO  Detailed event scraped: Jay Melodyz @TOATS 04/24
[apify.posh-vip runId:SuZE3Qpfs9I3OEuNU] -> 2026-04-01T16:50:57.695Z INFO  Progress: 46 events scraped

Saved Posh results as parquet file locally

In [87]:
#Getting event level results
posh_results_df = big_results_df.copy()
posh_results_df = posh_results_df.sort_values(by=["attendingCount"], ascending=False)

#Getting organizer level resutls
organizer_df = posh_results_df[["organizerName", "organizer", "organizerId"]].drop_duplicates(subset=['organizerId']).reset_index(drop=True)

#number of events per organizer
num_events_df = posh_results_df.groupby(["organizerId"]).agg(num_events = ('organizerId', 'count'))

# Expand 'data' column into new columns
new_cols = pd.json_normalize(organizer_df['organizer'])
#creating final organizer df
organizer_df_final = pd.concat([organizer_df.drop(columns=['organizer']), new_cols.drop(columns=['id','logo','currency','country','name'])], axis=1)
organizer_df_final = organizer_df_final.merge(num_events_df, on="organizerId", how="left")

In [105]:
# creating list of organizer urls to crawl
list_of_organizer_urls = organizer_df_final['url'].tolist()

In [107]:
import re

def add_g_to_posh_links(links):
    return [re.sub(r"(https://posh.vip/)([^/]+)$", r"\1g/\2", link) for link in links]


converted_urls = add_g_to_posh_links(list_of_organizer_urls)
print(converted_urls)

# Assuming converted_urls is already defined as your list of URLs
url_dicts = [{"url": url} for url in converted_urls]
print(len(url_dicts))

['https://posh.vip/g/secretsociety', 'https://posh.vip/g/ILOV3RNB', 'https://posh.vip/g/malavida', 'https://posh.vip/g/only-the-crew-llc', 'https://posh.vip/g/eastendballroom', 'https://posh.vip/g/twins-night-club', 'https://posh.vip/g/artchives', 'https://posh.vip/g/secretdiscosociety', 'https://posh.vip/g/where-yall-at-though', 'https://posh.vip/g/afroexpress-1', 'https://posh.vip/g/perreo-club', 'https://posh.vip/g/riviere-austin', 'https://posh.vip/g/aerolifeshows', 'https://posh.vip/g/sumn2say', 'https://posh.vip/g/nidasnexus', 'https://posh.vip/g/underground-faith', 'https://posh.vip/g/txst-nupes', 'https://posh.vip/g/lovemorernb', 'https://posh.vip/g/chas-and-champ', 'https://posh.vip/g/legvcy-events', 'https://posh.vip/g/events-by-samantha-2', 'https://posh.vip/g/punchline-at-the-pole', 'https://posh.vip/g/lez-in-the-capital', 'https://posh.vip/g/chunk-bros', 'https://posh.vip/g/SoulBloom', 'https://posh.vip/g/yuli', 'https://posh.vip/g/amplify-edm', 'https://posh.vip/g/events-by-wooskii', 'https://posh.vip/g/revelatx', 'https://posh.vip/g/halfdays', 'https://posh.vip/g/mirrormirror', 'https://posh.vip/g/project-pure', 'https://posh.vip/g/high-performance-collective', 'https://posh.vip/g/figbeard', 'https://posh.vip/g/all-daie-cold-pressed-juice', 'https://posh.vip/g/keep-austin-hard-events-1', 'https://posh.vip/g/east-end-events', 'https://posh.vip/g/my-birthday-3', 'https://posh.vip/g/whohotterpromotions', 'https://posh.vip/g/mom-dad', 'https://posh.vip/g/studio-201', 'https://posh.vip/g/justforfriends', 'https://posh.vip/g/solwomen', 'https://posh.vip/g/soireesets', 'https://posh.vip/g/cafe-grooves', 'https://posh.vip/g/kay-1', 'https://posh.vip/g/vantaathletics', 'https://posh.vip/g/frexh-produce', 'https://posh.vip/g/medicine-waves', 'https://posh.vip/g/finke-haus', 'https://posh.vip/g/hearts-in-harmony', 'https://posh.vip/g/salihah-barnett', 'https://posh.vip/g/bolm-arts', 'https://posh.vip/g/hotgirlpilates', 'https://posh.vip/g/plughub-austin', 'https://posh.vip/g/elemental', 'https://posh.vip/g/lazydaze-south-austin', 'https://posh.vip/g/urban-hills-design', 'https://posh.vip/g/house-of-plant-music', 'https://posh.vip/g/iyania', 'https://posh.vip/g/atxsupperclub', 'https://posh.vip/g/madewell-productions', 'https://posh.vip/g/all-good-things-studio', 'https://posh.vip/g/lucys-rock', 'https://posh.vip/g/keep-austin-live', 'https://posh.vip/g/ebonixintl', 'https://posh.vip/g/flow-yoga-cedar-park', 'https://posh.vip/g/flow-yoga-north-loop', 'https://posh.vip/g/black-women-of-south-austin', 'https://posh.vip/g/ruffhouse-collective', 'https://posh.vip/g/flow-yoga-south-congress', 'https://posh.vip/g/freelabelnet-1', 'https://posh.vip/g/sonus-productions', 'https://posh.vip/g/austin-yoga-club', 'https://posh.vip/g/frontline-ent', 'https://posh.vip/g/brand-by-zanders', 'https://posh.vip/g/themove-atx', 'https://posh.vip/g/ssk-labs', 'https://posh.vip/g/tapville-social', 'https://posh.vip/g/slink-studios-media', 'https://posh.vip/g/methodthree', 'https://posh.vip/g/pete-giza', 'https://posh.vip/g/firehouse-lounge', 'https://posh.vip/g/hues-of-faith', 'https://posh.vip/g/ts-productions', 'https://posh.vip/g/luna-rooftop-atx', 'https://posh.vip/g/x-spot-events', 'https://posh.vip/g/pickleland', 'https://posh.vip/g/balledjo-american-social-guild', 'https://posh.vip/g/craftery-tx', 'https://posh.vip/g/iyania', 'https://posh.vip/g/anis-day-night', 'https://posh.vip/g/aduro-film', 'https://posh.vip/g/national-business-expo', 'https://posh.vip/g/soniquarium', 'https://posh.vip/g/the-concord', 'https://posh.vip/g/shuffle-hq', 'https://posh.vip/g/overlyturnt', 'https://posh.vip/g/motion-university', 'https://posh.vip/g/cowboy-kim-presents', 'https://posh.vip/g/hostile-fest', 'https://posh.vip/g/az-vip-1', 'https://posh.vip/g/day-and-night-gallery', 'https://posh.vip/g/pilates-x-mia']
104

In [111]:
#chunking urls into groups of 10 to avoid overloading the system
chunk_size = 10
all_results = []

for i in range(0, len(converted_urls), chunk_size):
    # Get the current chunk
    chunk_urls = converted_urls[i:i+chunk_size]
    url_dicts = [{"url": url} for url in chunk_urls]
    
    test_posh = {
        "startUrls": url_dicts,
        "maxEvents": 2,
        "scrapeEventDetails": True
    }
    
    group_pulls = fetch_skip_trace(test_posh)
    all_results.extend(group_pulls)
    print(f"Processed chunk {i//chunk_size + 1}, got {len(group_pulls)} results")
    
#store as parquet file locally
run_id = str(int(time.time()))
group_pulls_df = pd.DataFrame(all_results)
group_pulls_df.to_parquet(f"posh_group_results_{run_id}.parquet", index=False)
print(f"Saved {len(all_results)} total Posh results as parquet file locally")

[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> Status: RUNNING, Message:
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:07.768Z ACTOR: Pulling container image of build VGlEYq35ZQlbL044v from registry.
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:07.770Z ACTOR: Creating container.
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:07.825Z ACTOR: Starting container.
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:07.827Z ACTOR: Running under "LIMITED_PERMISSIONS" permission level.
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:09.761Z INFO  System info {"apifyVersion":"3.5.2","apifyClientVersion":"2.21.0","crawleeVersion":"3.15.3","osType":"Linux","nodeVersion":"v20.19.6"}
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:09.913Z INFO  Starting Posh.vip scraper {"startUrlCount":10,"scrapeEventDetails":true,"maxEvents":2}
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:09.915Z INFO  Detected group page: https://posh.vip/g/secretsociety
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:09.917Z INFO  Detected group page: https://posh.vip/g/ILOV3RNB
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:09.918Z INFO  Detected group page: https://posh.vip/g/malavida
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:09.920Z INFO  Detected group page: https://posh.vip/g/only-the-crew-llc
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:09.922Z INFO  Detected group page: https://posh.vip/g/eastendballroom
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:09.923Z INFO  Detected group page: https://posh.vip/g/twins-night-club
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:09.925Z INFO  Detected group page: https://posh.vip/g/artchives
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:09.927Z INFO  Detected group page: https://posh.vip/g/secretdiscosociety
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:09.928Z INFO  Detected group page: https://posh.vip/g/where-yall-at-though
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:09.930Z INFO  Detected group page: https://posh.vip/g/afroexpress-1
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> Status: RUNNING, Message: Starting the crawler.
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.095Z INFO  CheerioCrawler: Starting the crawler.
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.609Z INFO  Processing group page: ILOV3RNB
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.610Z INFO  Fetching group data for: ILOV3RNB
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.618Z INFO  Processing group page: afroexpress-1
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.621Z INFO  Fetching group data for: afroexpress-1
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.626Z INFO  Processing group page: malavida
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.628Z INFO  Fetching group data for: malavida
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.645Z INFO  Processing group page: artchives
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.647Z INFO  Fetching group data for: artchives
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.652Z INFO  Processing group page: where-yall-at-though
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.654Z INFO  Fetching group data for: where-yall-at-though
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.658Z INFO  Processing group page: twins-night-club
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.660Z INFO  Fetching group data for: twins-night-club
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.666Z INFO  Processing group page: only-the-crew-llc
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.668Z INFO  Fetching group data for: only-the-crew-llc
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.670Z INFO  Processing group page: secretsociety
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.671Z INFO  Fetching group data for: secretsociety
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.673Z INFO  Processing group page: secretdiscosociety
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.675Z INFO  Fetching group data for: secretdiscosociety
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.676Z INFO  Processing group page: eastendballroom
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.678Z INFO  Fetching group data for: eastendballroom
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.762Z INFO  Fetched group "Afro-Express" with 5 events
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.766Z INFO  Fetched group "Artchives" with 4 events
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.773Z INFO  Fetched group "MALA VIDA" with 31 events
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.785Z INFO  Fetched group "EAST END BALLROOM" with 45 events
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.798Z INFO  Fetched group "Only The Crew" with 30 events
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.805Z INFO  Fetched group "Ilov3rnb" with 39 events
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.809Z INFO  Fetched group "Where Y'all At Though" with 42 events
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.812Z INFO  Fetched group "Twins Rooftop & Nightclub" with 51 events
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.816Z INFO  Group info stored: EAST END BALLROOM
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.819Z INFO  Group info stored: Artchives
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.821Z INFO  Group info stored: Only The Crew
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.824Z INFO  Group info stored: Ilov3rnb
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.829Z INFO  Group info stored: Afro-Express
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.833Z INFO  Group info stored: MALA VIDA
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.843Z INFO  Group info stored: Where Y'all At Though
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.856Z INFO  Fetched group "Events by secret society" with 127 events
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.866Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.875Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.877Z INFO  Group info stored: Events by secret society
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.881Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.884Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.888Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.893Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.908Z INFO  Fetched group "Secret Disco Society" with 152 events
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.909Z INFO  Group info stored: Twins Rooftop & Nightclub
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.913Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.936Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.942Z INFO  Group info stored: Secret Disco Society
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:10.982Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.016Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.250Z INFO  Scraping detailed event: perreo-2000-y2k-reggaeton-1
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.266Z INFO  Scraping detailed event: press-play-independence-edition
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.288Z INFO  Scraping detailed event: drunk-and-nasty-otcxbaewatch-events
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.332Z INFO  No search data available, fetching tickets separately for 68bf332cbf21b97ac2fe6ad2
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.338Z INFO  Scraping detailed event: pitch-black-2
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.377Z INFO  Scraping detailed event: black-austin-parks-ride
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.380Z INFO  Fetched 3 tickets for event 68bf332cbf21b97ac2fe6ad2
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.388Z INFO  Scraping detailed event: creative-kin
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.390Z INFO  No search data available, fetching tickets separately for 68e3057a747bf3df1659de7a
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.393Z INFO  No search data available, fetching tickets separately for 6792f62a1ffbdaaf11f5d481
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.408Z INFO  Scraping detailed event: -dont-miss-east-end-fm-w-the-droptines
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.414Z INFO  No search data available, fetching tickets separately for 68c35f2f6bbceb7fa0a8bb9d
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.428Z INFO  Scraping detailed event: black-pistol-fire-show
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.442Z INFO  No search data available, fetching tickets separately for 68bf6048698b75c741abc382
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.452Z INFO  No search data available, fetching tickets separately for 65d2b88fcec1e0e6eac4137d
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.458Z INFO  No search data available, fetching tickets separately for 684c621110c209438fc521eb
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.460Z INFO  Fetched 2 tickets for event 68c35f2f6bbceb7fa0a8bb9d
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.463Z INFO  Fetched 4 tickets for event 6792f62a1ffbdaaf11f5d481
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.480Z INFO  Fetched 2 tickets for event 68bf6048698b75c741abc382
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.485Z INFO  Fetched 1 tickets for event 68e3057a747bf3df1659de7a
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.493Z INFO  Fetched 1 tickets for event 65d2b88fcec1e0e6eac4137d
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.511Z INFO  Detailed event scraped: “DRUNK AND NASTY”: OTC x BAEWATCH EVENTS
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.512Z INFO  Progress: 1 events scraped
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.514Z INFO  Detailed event scraped: Press Play: Independence Edition
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.516Z INFO  Progress: 2 events scraped
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.517Z INFO  Fetched 1 tickets for event 684c621110c209438fc521eb
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.523Z INFO  Detailed event scraped: Pitch Black
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.524Z INFO  Progress: 3 events scraped
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.533Z INFO  No search data available, fetching tickets separately for 67bf84e034ea02de252acc59
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.539Z INFO  Detailed event scraped: Black Austin Parks Ride
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.541Z INFO  Progress: 4 events scraped
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.543Z INFO  Detailed event scraped: Perreo 2000 Y2k Reggaeton Houston
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.545Z INFO  Progress: 5 events scraped
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.546Z INFO  Detailed event scraped: CreativeKIN
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.548Z INFO  Progress: 6 events scraped
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.588Z INFO  Detailed event scraped: 🎸 Don't Miss EAST END FM w/ THE DROPTINES!
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.590Z INFO  Progress: 7 events scraped
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.630Z INFO  Fetched 1 tickets for event 67bf84e034ea02de252acc59
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.675Z INFO  Detailed event scraped: Black Pistol Fire Show
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:11.677Z INFO  Progress: 8 events scraped
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:12.361Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:12.846Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:13.683Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:13.697Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:13.700Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:13.705Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:13.783Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:13.794Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:13.865Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:13.894Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:14.029Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:14.192Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:14.270Z INFO  CheerioCrawler: All requests from the queue have been processed, the crawler will shut down.
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:14.420Z INFO  CheerioCrawler: Final request statistics: {"requestsFinished":30,"requestsFailed":0,"retryHistogram":[30],"requestAvgFailedDurationMillis":null,"requestAvgFinishedDurationMillis":1158,"requestsFinishedPerMinute":400,"requestsFailedPerMinute":0,"requestTotalDurationMillis":34751,"requestsTotal":30,"crawlerRuntimeMillis":4501}
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:14.422Z INFO  CheerioCrawler: Finished! Total 30 requests: 30 succeeded, 0 failed. {"terminal":true}
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> Status: RUNNING, Message: Finished! Total 30 requests: 30 succeeded, 0 failed.
[apify.posh-vip runId:CgB7HodsvgS7cMvd1] -> 2026-04-01T17:21:14.423Z INFO  Crawler finished. Total events scraped: 8

Processed chunk 1, got 18 results

[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> Status: RUNNING, Message:
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:21.324Z ACTOR: Pulling container image of build VGlEYq35ZQlbL044v from registry.
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:21.326Z ACTOR: Creating container.
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:21.414Z ACTOR: Starting container.
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:21.415Z ACTOR: Running under "LIMITED_PERMISSIONS" permission level.
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:22.544Z INFO  System info {"apifyVersion":"3.5.2","apifyClientVersion":"2.21.0","crawleeVersion":"3.15.3","osType":"Linux","nodeVersion":"v20.19.6"}
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:22.623Z INFO  Starting Posh.vip scraper {"startUrlCount":10,"scrapeEventDetails":true,"maxEvents":2}
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:22.624Z INFO  Detected group page: https://posh.vip/g/perreo-club
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:22.624Z INFO  Detected group page: https://posh.vip/g/riviere-austin
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:22.624Z INFO  Detected group page: https://posh.vip/g/aerolifeshows
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:22.625Z INFO  Detected group page: https://posh.vip/g/sumn2say
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:22.625Z INFO  Detected group page: https://posh.vip/g/nidasnexus
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:22.625Z INFO  Detected group page: https://posh.vip/g/underground-faith
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:22.625Z INFO  Detected group page: https://posh.vip/g/txst-nupes
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:22.625Z INFO  Detected group page: https://posh.vip/g/lovemorernb
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:22.626Z INFO  Detected group page: https://posh.vip/g/chas-and-champ
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:22.626Z INFO  Detected group page: https://posh.vip/g/legvcy-events
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:22.826Z INFO  CheerioCrawler: Starting the crawler.
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.291Z INFO  Processing group page: riviere-austin
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.292Z INFO  Fetching group data for: riviere-austin
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.300Z INFO  Processing group page: aerolifeshows
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.301Z INFO  Fetching group data for: aerolifeshows
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.309Z INFO  Processing group page: legvcy-events
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.310Z INFO  Fetching group data for: legvcy-events
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.314Z INFO  Processing group page: lovemorernb
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.314Z INFO  Fetching group data for: lovemorernb
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.317Z INFO  Processing group page: perreo-club
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.318Z INFO  Fetching group data for: perreo-club
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.332Z INFO  Processing group page: chas-and-champ
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.333Z INFO  Fetching group data for: chas-and-champ
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.334Z INFO  Processing group page: sumn2say
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.335Z INFO  Fetching group data for: sumn2say
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.357Z INFO  Processing group page: underground-faith
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.358Z INFO  Fetching group data for: underground-faith
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.360Z INFO  Processing group page: txst-nupes
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.360Z INFO  Fetching group data for: txst-nupes
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.366Z INFO  Processing group page: nidasnexus
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.366Z INFO  Fetching group data for: nidasnexus
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.410Z INFO  Fetched group "Chas and Champ" with 1 events
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.414Z INFO  Fetched group "Riviere Austin" with 16 events
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.415Z INFO  Fetched group "AEROLIFESHOWS" with 19 events
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.429Z INFO  Fetched group "UNDERGROUND FAITH" with 1 events
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.430Z INFO  Fetched group "SUMN2SAY" with 2 events
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.441Z INFO  Fetched group "LEGVCY EVENTS" with 12 events
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.447Z INFO  Fetched group "Perreo Club" with 34 events
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.451Z INFO  Fetched group "TXST Nupes" with 2 events
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.456Z INFO  Group info stored: UNDERGROUND FAITH
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.461Z INFO  Group info stored: Riviere Austin
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.466Z INFO  Fetched group "NidasNexus" with 10 events
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.469Z INFO  Group info stored: AEROLIFESHOWS
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.471Z INFO  Group info stored: TXST Nupes
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.476Z INFO  Group info stored: SUMN2SAY
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.487Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.492Z INFO  Group info stored: Perreo Club
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.494Z INFO  Group info stored: Chas and Champ
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.501Z INFO  Group info stored: LEGVCY EVENTS
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.508Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.510Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.513Z INFO  Group info stored: NidasNexus
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.519Z INFO  Fetched group "Love More Rnb" with 129 events
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.522Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.525Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.532Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.544Z INFO  Group info stored: Love More Rnb
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.548Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.578Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.599Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> Status: RUNNING, Message: Starting the crawler.
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.623Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.822Z INFO  Scraping detailed event: sumn2say-album-release-w-boooka
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.846Z INFO  Scraping detailed event: february-16th-the-morning-aftershow
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.877Z INFO  Scraping detailed event: the-link-up-21
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.884Z INFO  Scraping detailed event: march-20th-wifigawd-cjtopoff-live-in-dallas-tx
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.887Z INFO  No search data available, fetching tickets separately for 698eb3ac9fff2c219433d96d
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.891Z INFO  Scraping detailed event: good-fridays-2025-11-29-8-0
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.900Z INFO  No search data available, fetching tickets separately for 69879f35862b37618e2f0417
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.931Z INFO  Fetched 1 tickets for event 698eb3ac9fff2c219433d96d
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.940Z INFO  No search data available, fetching tickets separately for 69c576f8f94cd3480e3b428c
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.941Z INFO  Fetched 2 tickets for event 69879f35862b37618e2f0417
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.944Z INFO  No search data available, fetching tickets separately for 6920843c6f2d7a757b9fd868
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.949Z INFO  No search data available, fetching tickets separately for 69a4c598960ec8f82429dbe1
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.975Z INFO  Scraping detailed event: mrs-krimson-kream
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.980Z INFO  Scraping detailed event: pretty-icy-1
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.982Z INFO  Fetched 1 tickets for event 6920843c6f2d7a757b9fd868
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.983Z INFO  Fetched 1 tickets for event 69c576f8f94cd3480e3b428c
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.986Z INFO  Fetched 4 tickets for event 69a4c598960ec8f82429dbe1
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.989Z INFO  Detailed event scraped: FEBRUARY 16th: The Morning After-Show
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.989Z INFO  Progress: 1 events scraped
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.993Z INFO  Detailed event scraped: SUMN2SAY: Album Release w/ Boooka
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:23.993Z INFO  Progress: 2 events scraped
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:24.031Z INFO  Detailed event scraped: MARCH 20th: WIFIGAWD & CJTOPOFF Live in Dallas, TX
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:24.032Z INFO  Progress: 3 events scraped
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:24.043Z INFO  Detailed event scraped: The Link Up
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:24.043Z INFO  Progress: 4 events scraped
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:24.046Z INFO  No search data available, fetching tickets separately for 69c6e66280dde1e36ff9ff35
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:24.055Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:24.079Z INFO  Detailed event scraped: GOOD FRIDAYS
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:24.079Z INFO  Progress: 5 events scraped
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:24.093Z INFO  Fetched 2 tickets for event 69c6e66280dde1e36ff9ff35
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:24.145Z INFO  No search data available, fetching tickets separately for 69b84bea713c1a7dd9abf822
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:24.148Z INFO  Detailed event scraped: Pretty Icy
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:24.148Z INFO  Progress: 6 events scraped
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:24.189Z INFO  Fetched 2 tickets for event 69b84bea713c1a7dd9abf822
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:24.215Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:24.226Z INFO  Detailed event scraped: MISS. KRIMSON & KREAM 2026
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:24.226Z INFO  Progress: 7 events scraped
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:24.257Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:24.288Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:24.299Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:24.308Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:24.363Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:24.376Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:24.382Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:24.518Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:24.818Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:24.924Z INFO  CheerioCrawler: All requests from the queue have been processed, the crawler will shut down.
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:25.070Z INFO  CheerioCrawler: Final request statistics: {"requestsFinished":28,"requestsFailed":0,"retryHistogram":[28],"requestAvgFailedDurationMillis":null,"requestAvgFinishedDurationMillis":485,"requestsFinishedPerMinute":688,"requestsFailedPerMinute":0,"requestTotalDurationMillis":13586,"requestsTotal":28,"crawlerRuntimeMillis":2443}
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:25.071Z INFO  CheerioCrawler: Finished! Total 28 requests: 28 succeeded, 0 failed. {"terminal":true}
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> 2026-04-01T17:21:25.072Z INFO  Crawler finished. Total events scraped: 7
[apify.posh-vip runId:Z7njdGkGuhzqqpRt6] -> Status: SUCCEEDED, Message: Starting the crawler.

Processed chunk 2, got 17 results

[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> Status: RUNNING, Message:
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:32.999Z ACTOR: Pulling container image of build VGlEYq35ZQlbL044v from registry.
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:33.001Z ACTOR: Creating container.
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:33.064Z ACTOR: Starting container.
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:33.065Z ACTOR: Running under "LIMITED_PERMISSIONS" permission level.
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:34.414Z INFO  System info {"apifyVersion":"3.5.2","apifyClientVersion":"2.21.0","crawleeVersion":"3.15.3","osType":"Linux","nodeVersion":"v20.19.6"}
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:34.511Z INFO  Starting Posh.vip scraper {"startUrlCount":10,"scrapeEventDetails":true,"maxEvents":2}
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:34.512Z INFO  Detected group page: https://posh.vip/g/events-by-samantha-2
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:34.513Z INFO  Detected group page: https://posh.vip/g/punchline-at-the-pole
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:34.513Z INFO  Detected group page: https://posh.vip/g/lez-in-the-capital
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:34.514Z INFO  Detected group page: https://posh.vip/g/chunk-bros
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:34.514Z INFO  Detected group page: https://posh.vip/g/SoulBloom
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:34.515Z INFO  Detected group page: https://posh.vip/g/yuli
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:34.515Z INFO  Detected group page: https://posh.vip/g/amplify-edm
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:34.516Z INFO  Detected group page: https://posh.vip/g/events-by-wooskii
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:34.516Z INFO  Detected group page: https://posh.vip/g/revelatx
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:34.516Z INFO  Detected group page: https://posh.vip/g/halfdays
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> Status: RUNNING, Message: Starting the crawler.
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:34.742Z INFO  CheerioCrawler: Starting the crawler.
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:36.968Z INFO  Processing group page: chunk-bros
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:36.969Z INFO  Fetching group data for: chunk-bros
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:37.064Z INFO  Fetched group "Chunk Bros" with 16 events
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:37.116Z INFO  Group info stored: Chunk Bros
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:37.148Z INFO  Processing group page: revelatx
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:37.148Z INFO  Fetching group data for: revelatx
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:37.179Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:37.240Z INFO  Fetched group "Revel ATX" with 81 events
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:37.262Z INFO  Group info stored: Revel ATX
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:37.308Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.168Z INFO  Processing group page: lez-in-the-capital
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.169Z INFO  Fetching group data for: lez-in-the-capital
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.175Z INFO  Processing group page: yuli
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.176Z INFO  Fetching group data for: yuli
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.180Z INFO  Processing group page: SoulBloom
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.181Z INFO  Fetching group data for: SoulBloom
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.198Z INFO  Processing group page: halfdays
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.198Z INFO  Fetching group data for: halfdays
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.214Z INFO  Processing group page: punchline-at-the-pole
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.214Z INFO  Fetching group data for: punchline-at-the-pole
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.221Z INFO  Fetched group "Lez in the Capital" with 16 events
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.247Z INFO  Group info stored: Lez in the Capital
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.259Z INFO  Fetched group "Yuli" with 3 events
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.270Z INFO  Fetched group "SoulBloom" with 3 events
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.280Z INFO  Group info stored: Yuli
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.293Z INFO  Fetched group "Punchline at the Pole" with 13 events
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.297Z INFO  Group info stored: SoulBloom
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.299Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.315Z INFO  Group info stored: Punchline at the Pole
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.341Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.345Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.367Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.463Z INFO  Processing group page: amplify-edm
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.463Z INFO  Fetching group data for: amplify-edm
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.467Z INFO  Processing group page: events-by-wooskii
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.467Z INFO  Fetching group data for: events-by-wooskii
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.475Z INFO  Fetched group "Halfdays" with 288 events
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.498Z INFO  Group info stored: Halfdays
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.516Z INFO  Processing group page: events-by-samantha-2
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.517Z INFO  Fetching group data for: events-by-samantha-2
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.536Z INFO  Fetched group "Events by Wooskii" with 11 events
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.550Z INFO  Fetched group "Amplify EDM" with 44 events
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.558Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.567Z INFO  Group info stored: Events by Wooskii
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.570Z INFO  Group info stored: Amplify EDM
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.609Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.623Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.822Z INFO  Fetched group "Events by Luxeart" with 62 events
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.861Z INFO  Group info stored: Events by Luxeart
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:38.923Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:40.559Z INFO  Scraping detailed event: -sxsw-popup-party-at-taqueria-10-de-10-dj-chunk-bros-live-
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:40.631Z INFO  No search data available, fetching tickets separately for 67ccbe8aed6fa4c0d5d6bc11
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:40.674Z INFO  Fetched 1 tickets for event 67ccbe8aed6fa4c0d5d6bc11
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:40.722Z INFO  Detailed event scraped: 🔥 SXSW Pop-Up Party at Taqueria 10 de 10 – DJ Chunk Bros Live! 🔥
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:40.723Z INFO  Progress: 1 events scraped
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:41.365Z INFO  Scraping detailed event: a-freaky-friday-2
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:41.429Z INFO  No search data available, fetching tickets separately for 66ff132e0df2603244d13cd3
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:41.450Z INFO  Scraping detailed event: yulis-birthday-dinner
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:41.492Z INFO  Fetched 1 tickets for event 66ff132e0df2603244d13cd3
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:41.514Z INFO  No search data available, fetching tickets separately for 67e9efff00fc33ab343be8b8
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:41.529Z INFO  Detailed event scraped: A Freaky Friday
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:41.530Z INFO  Progress: 2 events scraped
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:41.560Z INFO  Fetched 1 tickets for event 67e9efff00fc33ab343be8b8
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:41.634Z INFO  Detailed event scraped: Yuli’s Birthday Dinner
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:41.635Z INFO  Progress: 3 events scraped
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:41.899Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:42.226Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:42.744Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:44.548Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:44.749Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:45.050Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> Status: RUNNING, Message: Crawled 17/30 pages, 0 failed requests, desired concurrency 10.
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:45.348Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:45.465Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:45.758Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:45.965Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:46.155Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:46.558Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:47.163Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:47.680Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:48.032Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:50.751Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:50.756Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:50.973Z INFO  CheerioCrawler: All requests from the queue have been processed, the crawler will shut down.
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:51.117Z INFO  CheerioCrawler: Final request statistics: {"requestsFinished":30,"requestsFailed":0,"retryHistogram":[30],"requestAvgFailedDurationMillis":null,"requestAvgFinishedDurationMillis":4135,"requestsFinishedPerMinute":108,"requestsFailedPerMinute":0,"requestTotalDurationMillis":124045,"requestsTotal":30,"crawlerRuntimeMillis":16600}
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:51.117Z INFO  CheerioCrawler: Finished! Total 30 requests: 30 succeeded, 0 failed. {"terminal":true}
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> 2026-04-01T17:21:51.118Z INFO  Crawler finished. Total events scraped: 3
[apify.posh-vip runId:oo8Ue3OM4BNCZvuqU] -> Status: SUCCEEDED, Message: Crawled 17/30 pages, 0 failed requests, desired concurrency 10.

Processed chunk 3, got 13 results

[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> Status: RUNNING, Message:
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:21:58.905Z ACTOR: Pulling container image of build VGlEYq35ZQlbL044v from registry.
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:21:58.907Z ACTOR: Creating container.
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:21:58.943Z ACTOR: Starting container.
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:21:58.944Z ACTOR: Running under "LIMITED_PERMISSIONS" permission level.
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.095Z INFO  System info {"apifyVersion":"3.5.2","apifyClientVersion":"2.21.0","crawleeVersion":"3.15.3","osType":"Linux","nodeVersion":"v20.19.6"}
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.191Z INFO  Starting Posh.vip scraper {"startUrlCount":10,"scrapeEventDetails":true,"maxEvents":2}
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.193Z INFO  Detected group page: https://posh.vip/g/mirrormirror
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.194Z INFO  Detected group page: https://posh.vip/g/project-pure
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.196Z INFO  Detected group page: https://posh.vip/g/high-performance-collective
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.197Z INFO  Detected group page: https://posh.vip/g/figbeard
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.198Z INFO  Detected group page: https://posh.vip/g/all-daie-cold-pressed-juice
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.200Z INFO  Detected group page: https://posh.vip/g/keep-austin-hard-events-1
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.201Z INFO  Detected group page: https://posh.vip/g/east-end-events
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.202Z INFO  Detected group page: https://posh.vip/g/my-birthday-3
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.204Z INFO  Detected group page: https://posh.vip/g/whohotterpromotions
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.205Z INFO  Detected group page: https://posh.vip/g/mom-dad
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.422Z INFO  CheerioCrawler: Starting the crawler.
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.848Z INFO  Processing group page: east-end-events
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.849Z INFO  Fetching group data for: east-end-events
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.870Z INFO  Processing group page: all-daie-cold-pressed-juice
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.872Z INFO  Fetching group data for: all-daie-cold-pressed-juice
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.876Z INFO  Processing group page: my-birthday-3
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.877Z INFO  Fetching group data for: my-birthday-3
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.882Z INFO  Processing group page: mirrormirror
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.883Z INFO  Fetching group data for: mirrormirror
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.886Z INFO  Processing group page: project-pure
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.888Z INFO  Fetching group data for: project-pure
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.891Z INFO  Processing group page: mom-dad
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.892Z INFO  Fetching group data for: mom-dad
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.897Z INFO  Processing group page: figbeard
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.898Z INFO  Fetching group data for: figbeard
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.902Z INFO  Processing group page: keep-austin-hard-events-1
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.904Z INFO  Fetching group data for: keep-austin-hard-events-1
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.907Z INFO  Processing group page: high-performance-collective
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.909Z INFO  Fetching group data for: high-performance-collective
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.919Z INFO  Processing group page: whohotterpromotions
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.920Z INFO  Fetching group data for: whohotterpromotions
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.989Z INFO  Fetched group "All Daie Cold Pressed Juice" with 1 events
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.993Z INFO  Fetched group "PROJECT PURE" with 3 events
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.995Z INFO  Fetched group "Mom & Dad" with 2 events
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.997Z INFO  Fetched group "High Performance Collective" with 1 events
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:00.999Z INFO  Fetched group "My birthday" with 1 events
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.003Z INFO  Fetched group "Figbeard" with 5 events
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.027Z INFO  Fetched group "WhoHotterPromotions" with 1 events
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.033Z INFO  Fetched group "Mirror Mirror" with 20 events
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.037Z INFO  Fetched group "East End Events" with 20 events
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.039Z INFO  Fetched group "Keep Austin Hard Events" with 18 events
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.051Z INFO  Group info stored: Figbeard
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.054Z INFO  Group info stored: High Performance Collective
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.057Z INFO  Group info stored: All Daie Cold Pressed Juice
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.059Z INFO  Group info stored: Mom & Dad
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.061Z INFO  Group info stored: WhoHotterPromotions
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.063Z INFO  Group info stored: PROJECT PURE
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.064Z INFO  Group info stored: My birthday
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.066Z INFO  Group info stored: East End Events
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.068Z INFO  Group info stored: Mirror Mirror
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.073Z INFO  Group info stored: Keep Austin Hard Events
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.076Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.079Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.092Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.100Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.106Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.115Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.116Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.117Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.119Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.157Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.416Z INFO  Scraping detailed event: 420-runners-high
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.422Z INFO  Scraping detailed event: keep-austin-hard-hartshorn
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.429Z INFO  Scraping detailed event: fruit-tree-jamboree
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.434Z INFO  Scraping detailed event: spring-reset-refresh
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.438Z INFO  Scraping detailed event: chris-and-jalen-party-boat-2026
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> Status: RUNNING, Message: Starting the crawler.
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.442Z INFO  Scraping detailed event: casino-night-a-charity-fundraiser-benefitting-uaf
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.476Z INFO  Scraping detailed event: afterglow
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.484Z INFO  No search data available, fetching tickets separately for 69a708add09370c9c2ae494a
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.496Z INFO  No search data available, fetching tickets separately for 65a9a193a65133c60866681a
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.501Z INFO  Scraping detailed event: sorens-bday
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.507Z INFO  Scraping detailed event: project-pure-fashion-show-project-no02start-your-engines
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.509Z INFO  No search data available, fetching tickets separately for 680f83db15e4c9f8595f764f
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.513Z INFO  No search data available, fetching tickets separately for 690533949341b144ffa317fe
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.515Z INFO  No search data available, fetching tickets separately for 69c593b46d95c07b6a140b1e
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.524Z INFO  No search data available, fetching tickets separately for 69b84ee96c5e3a2934cd8ffe
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.536Z INFO  Fetched 1 tickets for event 69a708add09370c9c2ae494a
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.551Z INFO  No search data available, fetching tickets separately for 65c198a435c2e825e71a3df1
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.553Z INFO  Fetched 2 tickets for event 65a9a193a65133c60866681a
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.563Z INFO  No search data available, fetching tickets separately for 68e9328469555e130a74028d
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.568Z INFO  Fetched 1 tickets for event 69c593b46d95c07b6a140b1e
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.581Z INFO  Fetched 1 tickets for event 69b84ee96c5e3a2934cd8ffe
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.592Z INFO  Detailed event scraped: 4/20 RUNNERS HIGH
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.596Z INFO  Progress: 1 events scraped
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.597Z INFO  Fetched 3 tickets for event 680f83db15e4c9f8595f764f
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.602Z INFO  No search data available, fetching tickets separately for 68e9e873b32a6645f733c274
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.607Z INFO  Fetched 1 tickets for event 65c198a435c2e825e71a3df1
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.612Z INFO  Fetched 1 tickets for event 68e9328469555e130a74028d
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.615Z INFO  Detailed event scraped: Keep Austin Hard: Hartshorn
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.616Z INFO  Progress: 2 events scraped
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.618Z INFO  Fetched 7 tickets for event 690533949341b144ffa317fe
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.619Z INFO  Detailed event scraped: Chris And Jalen  Party  Boat 2026
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.620Z INFO  Progress: 3 events scraped
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.631Z INFO  Detailed event scraped: Reset & Refresh: Pilates, Sound Healing & Juice bar
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.633Z INFO  Progress: 4 events scraped
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.649Z INFO  Detailed event scraped: Fruit Tree Jamboree
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.651Z INFO  Progress: 5 events scraped
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.654Z INFO  Fetched 3 tickets for event 68e9e873b32a6645f733c274
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.666Z INFO  Detailed event scraped: Afterglow
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.667Z INFO  Progress: 6 events scraped
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.669Z INFO  Detailed event scraped: Casino Night: A Charity Fundraiser Benefitting UAF
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.671Z INFO  Progress: 7 events scraped
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.677Z INFO  Detailed event scraped: Sorens BDAY
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.679Z INFO  Progress: 8 events scraped
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.742Z INFO  Detailed event scraped: PROJECT PURE RUNWAY SHOW- PROJECT NO.02
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.743Z "START YOUR ENGINES"
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.744Z INFO  Progress: 9 events scraped
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.768Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.910Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.918Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.925Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:01.996Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:02.002Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:02.074Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:02.152Z INFO  CheerioCrawler: All requests from the queue have been processed, the crawler will shut down.
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:02.175Z INFO  CheerioCrawler: All requests from the queue have been processed, the crawler will shut down.
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:02.463Z INFO  CheerioCrawler: Final request statistics: {"requestsFinished":26,"requestsFailed":0,"retryHistogram":[26],"requestAvgFailedDurationMillis":null,"requestAvgFinishedDurationMillis":449,"requestsFinishedPerMinute":688,"requestsFailedPerMinute":0,"requestTotalDurationMillis":11683,"requestsTotal":26,"crawlerRuntimeMillis":2266}
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:02.464Z INFO  CheerioCrawler: Finished! Total 26 requests: 26 succeeded, 0 failed. {"terminal":true}
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> 2026-04-01T17:22:02.466Z INFO  Crawler finished. Total events scraped: 9
[apify.posh-vip runId:Q8aHP6VtSPwQdouia] -> Status: SUCCEEDED, Message: Starting the crawler.

Processed chunk 4, got 19 results

[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> Status: RUNNING, Message:
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:09.666Z ACTOR: Pulling container image of build VGlEYq35ZQlbL044v from registry.
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:10.588Z ACTOR: Creating container.
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:10.770Z ACTOR: Starting container.
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:10.771Z ACTOR: Running under "LIMITED_PERMISSIONS" permission level.
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:13.153Z INFO  System info {"apifyVersion":"3.5.2","apifyClientVersion":"2.21.0","crawleeVersion":"3.15.3","osType":"Linux","nodeVersion":"v20.19.6"}
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:13.296Z INFO  Starting Posh.vip scraper {"startUrlCount":10,"scrapeEventDetails":true,"maxEvents":2}
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:13.297Z INFO  Detected group page: https://posh.vip/g/studio-201
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:13.297Z INFO  Detected group page: https://posh.vip/g/justforfriends
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:13.298Z INFO  Detected group page: https://posh.vip/g/solwomen
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:13.298Z INFO  Detected group page: https://posh.vip/g/soireesets
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:13.299Z INFO  Detected group page: https://posh.vip/g/cafe-grooves
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:13.299Z INFO  Detected group page: https://posh.vip/g/kay-1
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:13.299Z INFO  Detected group page: https://posh.vip/g/vantaathletics
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:13.300Z INFO  Detected group page: https://posh.vip/g/frexh-produce
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:13.300Z INFO  Detected group page: https://posh.vip/g/medicine-waves
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:13.301Z INFO  Detected group page: https://posh.vip/g/finke-haus
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:13.616Z INFO  CheerioCrawler: Starting the crawler.
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.177Z INFO  Processing group page: finke-haus
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.178Z INFO  Fetching group data for: finke-haus
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.187Z INFO  Processing group page: justforfriends
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.188Z INFO  Fetching group data for: justforfriends
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.204Z INFO  Processing group page: soireesets
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.205Z INFO  Fetching group data for: soireesets
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.210Z INFO  Processing group page: cafe-grooves
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.210Z INFO  Fetching group data for: cafe-grooves
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.215Z INFO  Processing group page: kay-1
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.215Z INFO  Fetching group data for: kay-1
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.218Z INFO  Processing group page: frexh-produce
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.219Z INFO  Fetching group data for: frexh-produce
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.221Z INFO  Processing group page: vantaathletics
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.222Z INFO  Fetching group data for: vantaathletics
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.224Z INFO  Processing group page: solwomen
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.225Z INFO  Fetching group data for: solwomen
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.227Z INFO  Processing group page: studio-201
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.228Z INFO  Fetching group data for: studio-201
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.230Z INFO  Processing group page: medicine-waves
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> Status: RUNNING, Message: Starting the crawler.
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.231Z INFO  Fetching group data for: medicine-waves
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.315Z INFO  Fetched group "No Signal" with 2 events
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.318Z INFO  Fetched group "Finke Haus" with 1 events
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.324Z INFO  Fetched group "Frexh Produce" with 3 events
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.325Z INFO  Fetched group "SolWomen" with 1 events
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.327Z INFO  Fetched group "Vanta Athletics" with 19 events
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.332Z INFO  Fetched group "Medicine Waves" with 7 events
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.341Z INFO  Fetched group "Kay" with 1 events
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.341Z INFO  Fetched group "studio 201" with 2 events
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.365Z INFO  Fetched group "Café Grooves" with 15 events
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.369Z INFO  Fetched group "Soirée Sets" with 38 events
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.391Z INFO  Group info stored: No Signal
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.392Z INFO  Group info stored: SolWomen
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.394Z INFO  Group info stored: Frexh Produce
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.397Z INFO  Group info stored: Kay
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.402Z INFO  Group info stored: studio 201
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.407Z INFO  Group info stored: Café Grooves
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.411Z INFO  Group info stored: Soirée Sets
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.414Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.418Z INFO  Group info stored: Medicine Waves
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.440Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.452Z INFO  Group info stored: Vanta Athletics
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.456Z INFO  Group info stored: Finke Haus
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.459Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.473Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.475Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.477Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.480Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.481Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.484Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.525Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.752Z INFO  Scraping detailed event: highland-basement-party-euphoreaster-
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.762Z INFO  Scraping detailed event: a-social-wellness-experience
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.772Z INFO  Scraping detailed event: purim-atx-2026
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.807Z INFO  Scraping detailed event: malto
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.816Z INFO  Scraping detailed event: cafe-grooves
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.820Z INFO  No search data available, fetching tickets separately for 69c1625eb7e66161a4e4de7a
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.827Z INFO  Scraping detailed event: viva-mxico-at-la-victoria
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.850Z INFO  Scraping detailed event: raising-consciousness-ecstatic-dance-3
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.851Z INFO  No search data available, fetching tickets separately for 69ab38f0feb2c88632f18d1c
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.854Z INFO  No search data available, fetching tickets separately for 68efd792ebff3aa58248fcc1
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.862Z INFO  Scraping detailed event: frexh-produce-presents-rumba-del-agua-lake-travis-boat-party
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.865Z INFO  Fetched 1 tickets for event 69c1625eb7e66161a4e4de7a
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.884Z INFO  No search data available, fetching tickets separately for 682260410acd1dc0f02f03de
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.893Z INFO  Fetched 3 tickets for event 69ab38f0feb2c88632f18d1c
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.902Z INFO  No search data available, fetching tickets separately for 67eab4d9f3e1ce8edb4b478e
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.908Z INFO  Scraping detailed event: studio-201-grand-opening
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.931Z INFO  Fetched 3 tickets for event 68efd792ebff3aa58248fcc1
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.944Z INFO  No search data available, fetching tickets separately for 66cca1fa4fbd1016f6b35bd3
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.947Z INFO  No search data available, fetching tickets separately for 66a750dbb39899534ef54796
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.956Z INFO  Detailed event scraped: A Social Wellness Experience
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.956Z INFO  Progress: 1 events scraped
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.972Z INFO  No search data available, fetching tickets separately for 680beb1257b2cac7963b9f50
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.976Z INFO  Scraping detailed event: caf-grooves-morning-party
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.977Z INFO  Detailed event scraped: Highland Basement Party: EUPHOREASTER 🐣💫
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.978Z INFO  Progress: 2 events scraped
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.980Z INFO  No search data available, fetching tickets separately for 69bcb7615a390e5edcc685c2
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.985Z INFO  Fetched 1 tickets for event 66cca1fa4fbd1016f6b35bd3
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.991Z INFO  Detailed event scraped: PURIM NIGHT ATX
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.992Z INFO  Progress: 3 events scraped
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:14.994Z INFO  Fetched 4 tickets for event 67eab4d9f3e1ce8edb4b478e
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:15.016Z INFO  Fetched 3 tickets for event 680beb1257b2cac7963b9f50
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:15.024Z INFO  Fetched 4 tickets for event 66a750dbb39899534ef54796
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:15.032Z INFO  Detailed event scraped: Raising Consciousness Ecstatic Dance
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:15.033Z INFO  Progress: 4 events scraped
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:15.043Z INFO  Fetched 1 tickets for event 682260410acd1dc0f02f03de
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:15.048Z INFO  Fetched 3 tickets for event 69bcb7615a390e5edcc685c2
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:15.058Z INFO  Detailed event scraped: Frexh Produce Presents: RUMBA DEL AGUA – Lake Travis Boat Party
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:15.059Z INFO  Progress: 5 events scraped
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:15.070Z INFO  Detailed event scraped: Cafe Grooves
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:15.071Z INFO  Progress: 6 events scraped
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:15.086Z INFO  No search data available, fetching tickets separately for 67b36e5d1391c3028bcb3b78
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:15.102Z INFO  Detailed event scraped: M^ALTO
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:15.102Z INFO  Progress: 7 events scraped
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:15.103Z INFO  Detailed event scraped: studio 201 soft launch
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:15.104Z INFO  Progress: 8 events scraped
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:15.134Z INFO  Detailed event scraped: Viva México At La Victoria
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:15.135Z INFO  Progress: 9 events scraped
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:15.413Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:15.417Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:15.417Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:15.422Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:15.424Z INFO  Fetched 2 tickets for event 67b36e5d1391c3028bcb3b78
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:15.469Z INFO  Detailed event scraped: Café Grooves Morning Party
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:15.472Z INFO  Progress: 10 events scraped
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:15.574Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:15.940Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:16.025Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:16.085Z INFO  CheerioCrawler: All requests from the queue have been processed, the crawler will shut down.
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:16.333Z INFO  CheerioCrawler: Final request statistics: {"requestsFinished":27,"requestsFailed":0,"retryHistogram":[27],"requestAvgFailedDurationMillis":null,"requestAvgFinishedDurationMillis":603,"requestsFinishedPerMinute":534,"requestsFailedPerMinute":0,"requestTotalDurationMillis":16277,"requestsTotal":27,"crawlerRuntimeMillis":3033}
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:16.334Z INFO  CheerioCrawler: Finished! Total 27 requests: 27 succeeded, 0 failed. {"terminal":true}
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> 2026-04-01T17:22:16.335Z INFO  Crawler finished. Total events scraped: 10
[apify.posh-vip runId:0mmZ5cEWvKLZf6e1D] -> Status: SUCCEEDED, Message: Starting the crawler.

Processed chunk 5, got 20 results

[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> Status: RUNNING, Message:
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:23.624Z ACTOR: Pulling container image of build VGlEYq35ZQlbL044v from registry.
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:23.626Z ACTOR: Creating container.
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:23.686Z ACTOR: Starting container.
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:23.687Z ACTOR: Running under "LIMITED_PERMISSIONS" permission level.
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:24.838Z INFO  System info {"apifyVersion":"3.5.2","apifyClientVersion":"2.21.0","crawleeVersion":"3.15.3","osType":"Linux","nodeVersion":"v20.19.6"}
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:24.926Z INFO  Starting Posh.vip scraper {"startUrlCount":10,"scrapeEventDetails":true,"maxEvents":2}
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:24.927Z INFO  Detected group page: https://posh.vip/g/hearts-in-harmony
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:24.928Z INFO  Detected group page: https://posh.vip/g/salihah-barnett
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:24.928Z INFO  Detected group page: https://posh.vip/g/bolm-arts
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:24.929Z INFO  Detected group page: https://posh.vip/g/hotgirlpilates
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:24.929Z INFO  Detected group page: https://posh.vip/g/plughub-austin
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:24.929Z INFO  Detected group page: https://posh.vip/g/elemental
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:24.930Z INFO  Detected group page: https://posh.vip/g/lazydaze-south-austin
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:24.930Z INFO  Detected group page: https://posh.vip/g/urban-hills-design
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:24.931Z INFO  Detected group page: https://posh.vip/g/house-of-plant-music
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:24.931Z INFO  Detected group page: https://posh.vip/g/iyania
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.230Z INFO  CheerioCrawler: Starting the crawler.
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.716Z INFO  Processing group page: hotgirlpilates
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.717Z INFO  Fetching group data for: hotgirlpilates
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.737Z INFO  Processing group page: lazydaze-south-austin
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.738Z INFO  Fetching group data for: lazydaze-south-austin
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.742Z INFO  Processing group page: house-of-plant-music
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.743Z INFO  Fetching group data for: house-of-plant-music
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.748Z INFO  Processing group page: iyania
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.749Z INFO  Fetching group data for: iyania
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.753Z INFO  Processing group page: elemental
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.753Z INFO  Fetching group data for: elemental
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.757Z INFO  Processing group page: bolm-arts
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.758Z INFO  Fetching group data for: bolm-arts
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.760Z INFO  Processing group page: salihah-barnett
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.761Z INFO  Fetching group data for: salihah-barnett
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.762Z INFO  Processing group page: urban-hills-design
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.763Z INFO  Fetching group data for: urban-hills-design
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.765Z INFO  Processing group page: plughub-austin
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.766Z INFO  Fetching group data for: plughub-austin
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.769Z INFO  Processing group page: hearts-in-harmony
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.770Z INFO  Fetching group data for: hearts-in-harmony
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.845Z INFO  Fetched group "Iyania" with 2 events
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.851Z INFO  Fetched group "Urban Hills Design" with 1 events
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.853Z INFO  Fetched group "Hot Girl Pilates" with 28 events
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.856Z INFO  Fetched group "LazyDaze South Austin" with 1 events
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.862Z INFO  Fetched group "Bolm Arts" with 1 events
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.863Z INFO  Fetched group "ELEMENTAL" with 1 events
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.863Z INFO  Fetched group "Plughub Austin" with 1 events
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.870Z INFO  Fetched group "Hearts in Harmony" with 1 events
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.901Z INFO  Group info stored: ELEMENTAL
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.904Z INFO  Group info stored: Urban Hills Design
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.906Z INFO  Group info stored: Iyania
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.909Z INFO  Group info stored: LazyDaze South Austin
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.911Z INFO  Group info stored: Plughub Austin
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.913Z INFO  Group info stored: Bolm Arts
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.918Z INFO  Group info stored: Hearts in Harmony
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.920Z INFO  Group info stored: Hot Girl Pilates
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.922Z INFO  Fetched group "House Of Plant Music" with 1 events
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.926Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.934Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.936Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.938Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.951Z INFO  Group info stored: House Of Plant Music
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.956Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.975Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.977Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:25.982Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> Status: RUNNING, Message: Starting the crawler.
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.015Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.247Z INFO  Scraping detailed event: flowers-friends-2
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.253Z INFO  Scraping detailed event: drag-bingo-420-edition
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.260Z INFO  Scraping detailed event: austin-real-estate-social
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.267Z INFO  Scraping detailed event: sunset-park-pilates-walk
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.277Z INFO  Scraping detailed event: iyanias-24th
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.284Z INFO  Scraping detailed event: hearts-in-harmonybenefit-concert-for-tmp
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.294Z INFO  Scraping detailed event: elemental-earth
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.300Z INFO  Scraping detailed event: vile-bodies
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.302Z INFO  No search data available, fetching tickets separately for 69c82635eaba0f0c2380db20
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.319Z INFO  No search data available, fetching tickets separately for 69a5f7361cdb5c8e8a5e2f99
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.325Z INFO  No search data available, fetching tickets separately for 69b173d2804754b255095f08
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.326Z INFO  No search data available, fetching tickets separately for 680904fb26e3f64ec4ab4c51
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.327Z INFO  No search data available, fetching tickets separately for 69cc43c2f2cafc542fcc252d
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.330Z INFO  Scraping detailed event: park-pilates-walk
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.341Z INFO  No search data available, fetching tickets separately for 69767f9d2804df2196949ef5
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.359Z INFO  No search data available, fetching tickets separately for 69c16173120d27d38adea02e
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.360Z INFO  No search data available, fetching tickets separately for 69c049171d9a5561c90054f1
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.361Z INFO  Fetched 1 tickets for event 69a5f7361cdb5c8e8a5e2f99
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.370Z INFO  Fetched 1 tickets for event 680904fb26e3f64ec4ab4c51
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.372Z INFO  Fetched 1 tickets for event 69c82635eaba0f0c2380db20
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.375Z INFO  Fetched 1 tickets for event 69cc43c2f2cafc542fcc252d
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.377Z INFO  Fetched 1 tickets for event 69b173d2804754b255095f08
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.386Z INFO  Fetched 1 tickets for event 69767f9d2804df2196949ef5
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.402Z INFO  Fetched 1 tickets for event 69c16173120d27d38adea02e
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.406Z INFO  Fetched 5 tickets for event 69c049171d9a5561c90054f1
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.409Z INFO  No search data available, fetching tickets separately for 67f68f0403bcb155f5ae98b1
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.426Z INFO  Detailed event scraped: Drag Bingo - 420 Edition
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.426Z INFO  Progress: 1 events scraped
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.427Z INFO  Detailed event scraped: Austin Real Estate Social
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.427Z INFO  Progress: 2 events scraped
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.428Z INFO  Detailed event scraped: Iyania’s 24th
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.429Z INFO  Progress: 3 events scraped
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.432Z INFO  Detailed event scraped: Sunset Park Pilates + Walk✨
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.432Z INFO  Progress: 4 events scraped
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.433Z INFO  Detailed event scraped: Hearts in Harmony-Benefit Concert for TMP
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.433Z INFO  Progress: 5 events scraped
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.446Z INFO  Detailed event scraped: Flowers & Friends 2
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.447Z INFO  Progress: 6 events scraped
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.448Z INFO  Detailed event scraped: ELEMENTAL: EARTH
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.448Z INFO  Progress: 7 events scraped
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.450Z INFO  Fetched 2 tickets for event 67f68f0403bcb155f5ae98b1
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.454Z INFO  Detailed event scraped: Vile Bodies
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.455Z INFO  Progress: 8 events scraped
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.507Z INFO  Detailed event scraped: Park Pilates + Walk✨
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.507Z INFO  Progress: 9 events scraped
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.667Z INFO  Fetched group "Salihah Barnett" with 8 events
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.693Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.699Z INFO  Group info stored: Salihah Barnett
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.764Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.846Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:26.966Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:27.019Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:27.087Z INFO  CheerioCrawler: All requests from the queue have been processed, the crawler will shut down.
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:27.324Z INFO  CheerioCrawler: Final request statistics: {"requestsFinished":23,"requestsFailed":0,"retryHistogram":[23],"requestAvgFailedDurationMillis":null,"requestAvgFinishedDurationMillis":487,"requestsFinishedPerMinute":577,"requestsFailedPerMinute":0,"requestTotalDurationMillis":11205,"requestsTotal":23,"crawlerRuntimeMillis":2392}
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:27.325Z INFO  CheerioCrawler: Finished! Total 23 requests: 23 succeeded, 0 failed. {"terminal":true}
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> 2026-04-01T17:22:27.325Z INFO  Crawler finished. Total events scraped: 9
[apify.posh-vip runId:WLwNsNX6y2j9gxVZV] -> Status: SUCCEEDED, Message: Starting the crawler.

Processed chunk 6, got 19 results

[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> Status: RUNNING, Message:
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:34.181Z ACTOR: Pulling container image of build VGlEYq35ZQlbL044v from registry.
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:34.184Z ACTOR: Creating container.
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:34.252Z ACTOR: Starting container.
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:34.254Z ACTOR: Running under "LIMITED_PERMISSIONS" permission level.
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:36.234Z INFO  System info {"apifyVersion":"3.5.2","apifyClientVersion":"2.21.0","crawleeVersion":"3.15.3","osType":"Linux","nodeVersion":"v20.19.6"}
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:36.329Z INFO  Starting Posh.vip scraper {"startUrlCount":10,"scrapeEventDetails":true,"maxEvents":2}
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:36.331Z INFO  Detected group page: https://posh.vip/g/atxsupperclub
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:36.333Z INFO  Detected group page: https://posh.vip/g/madewell-productions
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:36.335Z INFO  Detected group page: https://posh.vip/g/all-good-things-studio
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:36.337Z INFO  Detected group page: https://posh.vip/g/lucys-rock
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:36.338Z INFO  Detected group page: https://posh.vip/g/keep-austin-live
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:36.340Z INFO  Detected group page: https://posh.vip/g/ebonixintl
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:36.342Z INFO  Detected group page: https://posh.vip/g/flow-yoga-cedar-park
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:36.343Z INFO  Detected group page: https://posh.vip/g/flow-yoga-north-loop
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:36.345Z INFO  Detected group page: https://posh.vip/g/black-women-of-south-austin
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:36.347Z INFO  Detected group page: https://posh.vip/g/ruffhouse-collective
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> Status: RUNNING, Message: Starting the crawler.
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:36.603Z INFO  CheerioCrawler: Starting the crawler.
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.173Z INFO  Processing group page: flow-yoga-cedar-park
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.174Z INFO  Fetching group data for: flow-yoga-cedar-park
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.190Z INFO  Processing group page: madewell-productions
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.192Z INFO  Fetching group data for: madewell-productions
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.207Z INFO  Processing group page: all-good-things-studio
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.209Z INFO  Fetching group data for: all-good-things-studio
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.229Z INFO  Processing group page: flow-yoga-north-loop
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.232Z INFO  Fetching group data for: flow-yoga-north-loop
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.234Z INFO  Processing group page: ebonixintl
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.236Z INFO  Fetching group data for: ebonixintl
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.238Z INFO  Processing group page: ruffhouse-collective
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.240Z INFO  Fetching group data for: ruffhouse-collective
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.243Z INFO  Processing group page: keep-austin-live
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.245Z INFO  Fetching group data for: keep-austin-live
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.247Z INFO  Processing group page: black-women-of-south-austin
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.252Z INFO  Fetching group data for: black-women-of-south-austin
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.254Z INFO  Processing group page: atxsupperclub
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.256Z INFO  Fetching group data for: atxsupperclub
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.258Z INFO  Processing group page: lucys-rock
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.260Z INFO  Fetching group data for: lucys-rock
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.319Z INFO  Fetched group "Flow yoga Cedar Park" with 48 events
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.328Z INFO  Fetched group "Ruffhouse Collective" with 1 events
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.330Z INFO  Fetched group "Ebonix" with 3 events
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.331Z INFO  Fetched group "Madewell Productions" with 14 events
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.335Z INFO  Fetched group "Black Women of South Austin" with 3 events
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.344Z INFO  Fetched group "Lucy's Rock" with 9 events
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.378Z INFO  Fetched group "All Good Things Studio" with 16 events
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.380Z INFO  Fetched group "Keep Austin Live" with 1 events
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.382Z INFO  Fetched group "Flow Yoga North loop" with 35 events
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.386Z INFO  Group info stored: Flow yoga Cedar Park
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.389Z INFO  Group info stored: Keep Austin Live
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.391Z INFO  Group info stored: All Good Things Studio
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.393Z INFO  Group info stored: Ebonix
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.395Z INFO  Group info stored: Madewell Productions
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.397Z INFO  Group info stored: Black Women of South Austin
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.399Z INFO  Group info stored: Ruffhouse Collective
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.403Z INFO  Group info stored: Flow Yoga North loop
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.410Z INFO  Group info stored: Lucy's Rock
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.430Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.438Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.442Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.447Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.449Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.459Z INFO  Fetched group "ATX Supper Club" with 78 events
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.461Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.463Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.467Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.506Z INFO  Group info stored: ATX Supper Club
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.523Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.568Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.725Z INFO  Scraping detailed event: yoga-in-the-park-7
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.733Z INFO  Scraping detailed event: deadbeat-nightlife-planet-k-4212026
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.746Z INFO  Scraping detailed event: munchies-a-movie-how-high
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.754Z INFO  Scraping detailed event: the-future-is-femme-1
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.759Z INFO  Scraping detailed event: all-good-things-movement-x-faded-moon
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.763Z INFO  Scraping detailed event: street-team-day-4-empowher
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.782Z INFO  No search data available, fetching tickets separately for 6874df2f67bcd83b69e9a5c1
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.796Z INFO  No search data available, fetching tickets separately for 69ac57a2ec1e269e4d97447f
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.800Z INFO  No search data available, fetching tickets separately for 69caa7f0a8b7eb61bd455e3d
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.819Z INFO  No search data available, fetching tickets separately for 697cf8efde3bae4f47ea33ec
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.824Z INFO  Fetched 2 tickets for event 6874df2f67bcd83b69e9a5c1
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.829Z INFO  No search data available, fetching tickets separately for 67b52009981f8f73724c59e6
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.831Z INFO  No search data available, fetching tickets separately for 6832d77b475d92a413a265db
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.839Z INFO  Fetched 1 tickets for event 69caa7f0a8b7eb61bd455e3d
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.853Z INFO  Scraping detailed event: free-community-class
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.858Z INFO  Scraping detailed event: stand-up-comedy-sit-down-yoga
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.863Z INFO  Fetched 1 tickets for event 697cf8efde3bae4f47ea33ec
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.864Z INFO  Fetched 1 tickets for event 69ac57a2ec1e269e4d97447f
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.867Z INFO  Fetched 1 tickets for event 67b52009981f8f73724c59e6
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.888Z INFO  Fetched 1 tickets for event 6832d77b475d92a413a265db
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.900Z INFO  Detailed event scraped: Munchies & A Movie : How High
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.901Z INFO  Progress: 1 events scraped
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.903Z INFO  Detailed event scraped: All Good Things Movement
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.905Z INFO  Progress: 2 events scraped
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.907Z INFO  No search data available, fetching tickets separately for 6874e48967bcd83b69e9b522
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.908Z INFO  Detailed event scraped: THE FUTURE IS FEMME
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.910Z INFO  Progress: 3 events scraped
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.912Z INFO  No search data available, fetching tickets separately for 68a8882ae8bc59dbee88f431
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.914Z INFO  Detailed event scraped: Deadbeat Nightlife @ Planet K 4/21/2026
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.915Z INFO  Progress: 4 events scraped
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.928Z INFO  Detailed event scraped: Yoga in the Park
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.929Z INFO  Progress: 5 events scraped
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.941Z INFO  Detailed event scraped: STREET TEAM DAY 4 EMPOWHER
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.943Z INFO  Progress: 6 events scraped
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.946Z INFO  Fetched 1 tickets for event 6874e48967bcd83b69e9b522
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:37.956Z INFO  Fetched 1 tickets for event 68a8882ae8bc59dbee88f431
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:38.004Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:38.012Z INFO  Detailed event scraped: Free Community Class
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:38.013Z INFO  Progress: 7 events scraped
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:38.035Z INFO  Detailed event scraped: Stand Up Comedy, Sit Down Yoga
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:38.037Z INFO  Progress: 8 events scraped
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:38.056Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:38.134Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:38.249Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:38.334Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:38.461Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:38.565Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:38.572Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:38.863Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:42.204Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:42.310Z INFO  CheerioCrawler: All requests from the queue have been processed, the crawler will shut down.
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:42.366Z INFO  CheerioCrawler: All requests from the queue have been processed, the crawler will shut down.
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:42.525Z INFO  CheerioCrawler: Final request statistics: {"requestsFinished":28,"requestsFailed":0,"retryHistogram":[28],"requestAvgFailedDurationMillis":null,"requestAvgFinishedDurationMillis":665,"requestsFinishedPerMinute":271,"requestsFailedPerMinute":0,"requestTotalDurationMillis":18621,"requestsTotal":28,"crawlerRuntimeMillis":6190}
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:42.527Z INFO  CheerioCrawler: Finished! Total 28 requests: 28 succeeded, 0 failed. {"terminal":true}
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> 2026-04-01T17:22:42.528Z INFO  Crawler finished. Total events scraped: 8
[apify.posh-vip runId:X5Q8UGHcIPjs8XOcL] -> Status: SUCCEEDED, Message: Starting the crawler.

Processed chunk 7, got 18 results

[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> Status: RUNNING, Message:
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:50.481Z ACTOR: Pulling container image of build VGlEYq35ZQlbL044v from registry.
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:50.483Z ACTOR: Creating container.
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:50.554Z ACTOR: Starting container.
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:50.557Z ACTOR: Running under "LIMITED_PERMISSIONS" permission level.
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:51.674Z INFO  System info {"apifyVersion":"3.5.2","apifyClientVersion":"2.21.0","crawleeVersion":"3.15.3","osType":"Linux","nodeVersion":"v20.19.6"}
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:51.777Z INFO  Starting Posh.vip scraper {"startUrlCount":10,"scrapeEventDetails":true,"maxEvents":2}
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:51.780Z INFO  Detected group page: https://posh.vip/g/flow-yoga-south-congress
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:51.781Z INFO  Detected group page: https://posh.vip/g/freelabelnet-1
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:51.783Z INFO  Detected group page: https://posh.vip/g/sonus-productions
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:51.785Z INFO  Detected group page: https://posh.vip/g/austin-yoga-club
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:51.786Z INFO  Detected group page: https://posh.vip/g/frontline-ent
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:51.788Z INFO  Detected group page: https://posh.vip/g/brand-by-zanders
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:51.790Z INFO  Detected group page: https://posh.vip/g/themove-atx
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:51.791Z INFO  Detected group page: https://posh.vip/g/ssk-labs
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:51.793Z INFO  Detected group page: https://posh.vip/g/tapville-social
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:51.795Z INFO  Detected group page: https://posh.vip/g/slink-studios-media
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.078Z INFO  CheerioCrawler: Starting the crawler.
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.509Z INFO  Processing group page: tapville-social
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.511Z INFO  Fetching group data for: tapville-social
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.519Z INFO  Processing group page: flow-yoga-south-congress
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.521Z INFO  Fetching group data for: flow-yoga-south-congress
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.523Z INFO  Processing group page: austin-yoga-club
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.525Z INFO  Fetching group data for: austin-yoga-club
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.535Z INFO  Processing group page: sonus-productions
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.536Z INFO  Fetching group data for: sonus-productions
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.538Z INFO  Processing group page: slink-studios-media
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.540Z INFO  Fetching group data for: slink-studios-media
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.542Z INFO  Processing group page: brand-by-zanders
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.543Z INFO  Fetching group data for: brand-by-zanders
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.545Z INFO  Processing group page: themove-atx
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.547Z INFO  Fetching group data for: themove-atx
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.548Z INFO  Processing group page: ssk-labs
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.550Z INFO  Fetching group data for: ssk-labs
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.552Z INFO  Processing group page: frontline-ent
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.553Z INFO  Fetching group data for: frontline-ent
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.622Z INFO  Processing group page: freelabelnet-1
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.624Z INFO  Fetching group data for: freelabelnet-1
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.625Z INFO  Fetched group "Tapville Social" with 2 events
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.630Z INFO  Fetched group "Austin Yoga Club" with 1 events
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.632Z INFO  Fetched group "Slink Studios Media" with 1 events
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.636Z INFO  Fetched group "S.S.K. (LABS)" with 2 events
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.638Z INFO  Fetched group "Frontline Ent" with 1 events
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.640Z INFO  Fetched group "Brand By Zanders" with 1 events
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.641Z INFO  Fetched group "Sonus Productions " with 5 events
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.663Z INFO  Fetched group "The Move" with 47 events
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.671Z INFO  Group info stored: S.S.K. (LABS)
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.673Z INFO  Group info stored: Slink Studios Media
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.678Z INFO  Group info stored: Brand By Zanders
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.681Z INFO  Fetched group "Flow Yoga South Congress" with 82 events
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.683Z INFO  Group info stored: Frontline Ent
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.685Z INFO  Group info stored: Austin Yoga Club
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.686Z INFO  Group info stored: Sonus Productions
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.689Z INFO  Group info stored: Tapville Social
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.692Z INFO  Group info stored: The Move
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.702Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.704Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.706Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.708Z INFO  Group info stored: Flow Yoga South Congress
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.735Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.737Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.739Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.741Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.757Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.796Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.811Z INFO  Fetched group "FREELABEL.NET" with 1 events
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.837Z INFO  Group info stored: FREELABEL.NET
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.862Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.958Z INFO  Scraping detailed event: scentsorial-experience-with-ssk-labs-1
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:52.998Z INFO  Scraping detailed event: hierarchy
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.007Z INFO  Scraping detailed event: march-madness-2026-4-1-21-0
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.011Z INFO  Scraping detailed event: adult-easter-egg-hunt-4
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.018Z INFO  Scraping detailed event: sip-shop-a-curated-market
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.021Z INFO  No search data available, fetching tickets separately for 69a882d2e78de893c452a51c
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.040Z INFO  Scraping detailed event: hop-out-pop-up-photoshoot
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.047Z INFO  Scraping detailed event: danny-the-wildchild-houston
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.064Z INFO  Scraping detailed event: full-moon-sound-ceremony-1
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.065Z INFO  No search data available, fetching tickets separately for 69bc6139dcf260e83fcd7c86
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.068Z INFO  No search data available, fetching tickets separately for 698a3df9037b5ec4f5144119
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.070Z INFO  Fetched 2 tickets for event 69a882d2e78de893c452a51c
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.073Z INFO  No search data available, fetching tickets separately for 69b861e6045f551d11aaccd3
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.076Z INFO  Scraping detailed event: elevated-yoga-sound-bath-with-austin-yoga-club-lazydaze
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> Status: RUNNING, Message: Starting the crawler.
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.080Z INFO  No search data available, fetching tickets separately for 69ca56854ff9143a3c6acf11
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.103Z INFO  No search data available, fetching tickets separately for 68914769ea8e48ff8b0ab4b1
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.105Z INFO  Fetched 1 tickets for event 69bc6139dcf260e83fcd7c86
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.108Z INFO  No search data available, fetching tickets separately for 69c417b0b13e1fd89557a4f0
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.110Z INFO  Fetched 1 tickets for event 69b861e6045f551d11aaccd3
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.114Z INFO  Scraping detailed event: march-madness-2026-4-8-21-0
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.123Z INFO  Fetched 2 tickets for event 698a3df9037b5ec4f5144119
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.127Z INFO  Fetched 1 tickets for event 69ca56854ff9143a3c6acf11
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.130Z INFO  No search data available, fetching tickets separately for 689222d87603f335ddc90d48
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.148Z INFO  Fetched 3 tickets for event 68914769ea8e48ff8b0ab4b1
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.152Z INFO  Fetched 1 tickets for event 69c417b0b13e1fd89557a4f0
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.153Z INFO  Detailed event scraped: March Madness
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.155Z INFO  Progress: 1 events scraped
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.157Z INFO  Detailed event scraped: Scent Social: Sip, Snif N’ Scratch w/ S.S.K. (LABS)
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.158Z INFO  Progress: 2 events scraped
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.160Z INFO  Detailed event scraped: Adult Easter Egg Hunt
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.162Z INFO  Progress: 3 events scraped
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.164Z INFO  No search data available, fetching tickets separately for 69bb8394d97ef16048b9ac00
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.165Z INFO  No search data available, fetching tickets separately for 69b861e6045f551d11aaccd6
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.170Z INFO  Fetched 1 tickets for event 689222d87603f335ddc90d48
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.186Z INFO  Detailed event scraped: Sip & Shop: A Curated Market
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.188Z INFO  Progress: 4 events scraped
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.191Z INFO  Detailed event scraped: Hop Out Pop Up Photoshoot
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.193Z INFO  Progress: 5 events scraped
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.203Z INFO  Fetched 1 tickets for event 69bb8394d97ef16048b9ac00
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.206Z INFO  Detailed event scraped: DANNY THE WILDCHILD - HOUSTON
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.207Z INFO  Progress: 6 events scraped
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.209Z INFO  Fetched 1 tickets for event 69b861e6045f551d11aaccd6
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.211Z INFO  Detailed event scraped: Hierarchy
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.213Z INFO  Progress: 7 events scraped
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.218Z INFO  Detailed event scraped: Full Moon Sound Ceremony
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.220Z INFO  Progress: 8 events scraped
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.254Z INFO  Detailed event scraped: Elevated Yoga & Sound Bath @ Lazydaze
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.256Z INFO  Progress: 9 events scraped
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.263Z INFO  Detailed event scraped: March Madness
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.265Z INFO  Progress: 10 events scraped
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.411Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.421Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.447Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.469Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.505Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.601Z INFO  CheerioCrawler: All requests from the queue have been processed, the crawler will shut down.
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.752Z INFO  CheerioCrawler: Final request statistics: {"requestsFinished":25,"requestsFailed":0,"retryHistogram":[25],"requestAvgFailedDurationMillis":null,"requestAvgFinishedDurationMillis":424,"requestsFinishedPerMinute":762,"requestsFailedPerMinute":0,"requestTotalDurationMillis":10608,"requestsTotal":25,"crawlerRuntimeMillis":1969}
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.753Z INFO  CheerioCrawler: Finished! Total 25 requests: 25 succeeded, 0 failed. {"terminal":true}
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> 2026-04-01T17:22:53.755Z INFO  Crawler finished. Total events scraped: 10
[apify.posh-vip runId:bWuJhFcPqwRkh6VOh] -> Status: SUCCEEDED, Message: Starting the crawler.

Processed chunk 8, got 20 results

[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> Status: RUNNING, Message:
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:01.394Z ACTOR: Pulling container image of build VGlEYq35ZQlbL044v from registry.
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:01.400Z ACTOR: Creating container.
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:01.588Z ACTOR: Starting container.
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:01.589Z ACTOR: Running under "LIMITED_PERMISSIONS" permission level.
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:04.240Z INFO  System info {"apifyVersion":"3.5.2","apifyClientVersion":"2.21.0","crawleeVersion":"3.15.3","osType":"Linux","nodeVersion":"v20.19.6"}
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:04.351Z INFO  Starting Posh.vip scraper {"startUrlCount":10,"scrapeEventDetails":true,"maxEvents":2}
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:04.354Z INFO  Detected group page: https://posh.vip/g/methodthree
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:04.355Z INFO  Detected group page: https://posh.vip/g/pete-giza
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:04.356Z INFO  Detected group page: https://posh.vip/g/firehouse-lounge
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:04.356Z INFO  Detected group page: https://posh.vip/g/hues-of-faith
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:04.357Z INFO  Detected group page: https://posh.vip/g/ts-productions
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:04.358Z INFO  Detected group page: https://posh.vip/g/luna-rooftop-atx
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:04.358Z INFO  Detected group page: https://posh.vip/g/x-spot-events
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:04.359Z INFO  Detected group page: https://posh.vip/g/pickleland
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:04.359Z INFO  Detected group page: https://posh.vip/g/balledjo-american-social-guild
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:04.360Z INFO  Detected group page: https://posh.vip/g/craftery-tx
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> Status: RUNNING, Message: Starting the crawler.
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:04.591Z INFO  CheerioCrawler: Starting the crawler.
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.169Z INFO  Processing group page: balledjo-american-social-guild
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.170Z INFO  Fetching group data for: balledjo-american-social-guild
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.181Z INFO  Processing group page: ts-productions
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.181Z INFO  Fetching group data for: ts-productions
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.186Z INFO  Processing group page: pickleland
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.186Z INFO  Fetching group data for: pickleland
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.192Z INFO  Processing group page: luna-rooftop-atx
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.192Z INFO  Fetching group data for: luna-rooftop-atx
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.195Z INFO  Processing group page: hues-of-faith
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.195Z INFO  Fetching group data for: hues-of-faith
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.197Z INFO  Processing group page: x-spot-events
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.197Z INFO  Fetching group data for: x-spot-events
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.199Z INFO  Processing group page: methodthree
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.199Z INFO  Fetching group data for: methodthree
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.248Z INFO  Processing group page: craftery-tx
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.249Z INFO  Fetching group data for: craftery-tx
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.252Z INFO  Processing group page: firehouse-lounge
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.252Z INFO  Fetching group data for: firehouse-lounge
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.268Z INFO  Processing group page: pete-giza
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.268Z INFO  Fetching group data for: pete-giza
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.305Z INFO  Fetched group "Balledjo American Social Guild" with 23 events
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.308Z INFO  Fetched group "X Spot Events" with 17 events
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.310Z INFO  Fetched group "Hues of Faith" with 29 events
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.314Z INFO  Fetched group "TS PRODUCTIONS" with 3 events
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.370Z INFO  Group info stored: Hues of Faith
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.373Z INFO  Group info stored: X Spot Events
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.376Z INFO  Group info stored: TS PRODUCTIONS
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.379Z INFO  Fetched group "Pete Giza" with 1 events
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.382Z INFO  Group info stored: Balledjo American Social Guild
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.385Z INFO  Fetched group "Craftery TX" with 4 events
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.392Z INFO  Fetched group "LUNA ROOFTOP" with 82 events
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.402Z INFO  Group info stored: Pete Giza
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.412Z INFO  Group info stored: Craftery TX
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.416Z INFO  Fetched group "Firehouse Lounge" with 65 events
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.419Z INFO  Group info stored: LUNA ROOFTOP
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.425Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.435Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.438Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.443Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.456Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.467Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.473Z INFO  Group info stored: Firehouse Lounge
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.494Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.516Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.723Z INFO  Scraping detailed event: christian-girl-brunch-2026-4-12-19-0
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.764Z INFO  Scraping detailed event: xspot-afterglow-2026-1-11-7-0
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.775Z INFO  Scraping detailed event: bingo-madness-lazydaze
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.783Z INFO  Scraping detailed event: xspot-lunchbox-2026-1-6-21-0
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.789Z INFO  No search data available, fetching tickets separately for 69c7e30620e6c2eba5cd3f06
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.797Z INFO  Scraping detailed event: vinho-de-bossa-2026-1-16-4-0
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.801Z INFO  Scraping detailed event: vinho-de-bossa-11
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.816Z INFO  Scraping detailed event: decoupage-wooden-eggs-craft-mondays
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.835Z INFO  Scraping detailed event: pete-giza-experienc
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.836Z INFO  No search data available, fetching tickets separately for 69795832a03f024d3d29f1e6
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.841Z INFO  Fetched 1 tickets for event 69c7e30620e6c2eba5cd3f06
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.845Z INFO  No search data available, fetching tickets separately for 6941e0c297ffe4bf986be1ee
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.867Z INFO  No search data available, fetching tickets separately for 695495442ac296772455ed3c
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.867Z INFO  No search data available, fetching tickets separately for 69706781edfc47469f0011cc
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.873Z INFO  No search data available, fetching tickets separately for 69cc3a42859ea64f09ff3539
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.883Z INFO  Fetched 1 tickets for event 69795832a03f024d3d29f1e6
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.896Z INFO  Detailed event scraped: Christian Girl Brunch
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.896Z INFO  Progress: 1 events scraped
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.898Z INFO  Fetched 2 tickets for event 6941e0c297ffe4bf986be1ee
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.901Z INFO  No search data available, fetching tickets separately for 69c564391dc1028cd930fa42
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.907Z INFO  Fetched 1 tickets for event 695495442ac296772455ed3c
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.908Z INFO  Fetched 1 tickets for event 69706781edfc47469f0011cc
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.915Z INFO  Fetched 1 tickets for event 69cc3a42859ea64f09ff3539
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.932Z INFO  Detailed event scraped: BINGO MADNESS @ LAZYDAZE!
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.933Z INFO  Progress: 2 events scraped
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.947Z INFO  Detailed event scraped: Vinho De Bossa
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.948Z INFO  Progress: 3 events scraped
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.954Z INFO  Detailed event scraped: Sanctuary
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.955Z INFO  Progress: 4 events scraped
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.962Z INFO  Detailed event scraped: X-Spot Lunchbox
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.963Z INFO  Progress: 5 events scraped
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:05.967Z INFO  Fetched 1 tickets for event 69c564391dc1028cd930fa42
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:06.006Z INFO  Detailed event scraped: Decoupage Wooden Eggs - Craft Mondays
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:06.007Z INFO  Progress: 6 events scraped
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:06.013Z INFO  Detailed event scraped: Pete Giza Experience
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:06.013Z INFO  Progress: 7 events scraped
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:06.079Z INFO  Fetched group "M3" with 603 events
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:06.106Z INFO  Group info stored: M3
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:06.176Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:06.188Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:06.196Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:06.235Z INFO  Fetched group "Pickleland" with 1474 events
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:06.252Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:06.257Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:06.263Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:06.266Z INFO  Group info stored: Pickleland
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:06.270Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:06.304Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:06.308Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:06.473Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:06.619Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:06.632Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:06.672Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:07.174Z INFO  No search data available, fetching tickets separately for 6952bfcbb33893c6f056c944
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:07.218Z INFO  Fetched 1 tickets for event 6952bfcbb33893c6f056c944
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:07.316Z INFO  Detailed event scraped: Vinho De Bossa
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:07.317Z INFO  Progress: 8 events scraped
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:07.390Z INFO  CheerioCrawler: All requests from the queue have been processed, the crawler will shut down.
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:07.529Z INFO  CheerioCrawler: Final request statistics: {"requestsFinished":29,"requestsFailed":0,"retryHistogram":[29],"requestAvgFailedDurationMillis":null,"requestAvgFinishedDurationMillis":567,"requestsFinishedPerMinute":549,"requestsFailedPerMinute":0,"requestTotalDurationMillis":16452,"requestsTotal":29,"crawlerRuntimeMillis":3168}
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:07.530Z INFO  CheerioCrawler: Finished! Total 29 requests: 29 succeeded, 0 failed. {"terminal":true}
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> 2026-04-01T17:23:07.530Z INFO  Crawler finished. Total events scraped: 8
[apify.posh-vip runId:iy9ylOPw9c7ZhbK8l] -> Status: SUCCEEDED, Message: Starting the crawler.

Processed chunk 9, got 18 results

[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> Status: RUNNING, Message:
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:14.699Z ACTOR: Pulling container image of build VGlEYq35ZQlbL044v from registry.
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:14.701Z ACTOR: Creating container.
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:14.889Z ACTOR: Starting container.
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:14.889Z ACTOR: Running under "LIMITED_PERMISSIONS" permission level.
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:17.313Z INFO  System info {"apifyVersion":"3.5.2","apifyClientVersion":"2.21.0","crawleeVersion":"3.15.3","osType":"Linux","nodeVersion":"v20.19.6"}
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:17.412Z INFO  Starting Posh.vip scraper {"startUrlCount":10,"scrapeEventDetails":true,"maxEvents":2}
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:17.413Z INFO  Detected group page: https://posh.vip/g/iyania
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:17.414Z INFO  Detected group page: https://posh.vip/g/anis-day-night
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:17.414Z INFO  Detected group page: https://posh.vip/g/aduro-film
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:17.414Z INFO  Detected group page: https://posh.vip/g/national-business-expo
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:17.415Z INFO  Detected group page: https://posh.vip/g/soniquarium
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:17.415Z INFO  Detected group page: https://posh.vip/g/the-concord
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:17.415Z INFO  Detected group page: https://posh.vip/g/shuffle-hq
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:17.415Z INFO  Detected group page: https://posh.vip/g/overlyturnt
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:17.416Z INFO  Detected group page: https://posh.vip/g/motion-university
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:17.416Z INFO  Detected group page: https://posh.vip/g/cowboy-kim-presents
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> Status: RUNNING, Message: Starting the crawler.
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:17.659Z INFO  CheerioCrawler: Starting the crawler.
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.343Z INFO  Processing group page: soniquarium
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.343Z INFO  Fetching group data for: soniquarium
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.374Z INFO  Processing group page: national-business-expo
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.375Z INFO  Fetching group data for: national-business-expo
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.394Z INFO  Processing group page: overlyturnt
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.394Z INFO  Fetching group data for: overlyturnt
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.400Z INFO  Processing group page: iyania
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.400Z INFO  Fetching group data for: iyania
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.403Z INFO  Processing group page: the-concord
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.404Z INFO  Fetching group data for: the-concord
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.406Z INFO  Processing group page: cowboy-kim-presents
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.406Z INFO  Fetching group data for: cowboy-kim-presents
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.409Z INFO  Processing group page: aduro-film
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.410Z INFO  Fetching group data for: aduro-film
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.412Z INFO  Processing group page: shuffle-hq
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.413Z INFO  Fetching group data for: shuffle-hq
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.427Z INFO  Processing group page: anis-day-night
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.427Z INFO  Fetching group data for: anis-day-night
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.432Z INFO  Processing group page: motion-university
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.433Z INFO  Fetching group data for: motion-university
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.512Z INFO  Fetched group "Motion University" with 1 events
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.516Z INFO  Fetched group "Aduro Film" with 1 events
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.518Z INFO  Fetched group "OverlyTurnt" with 8 events
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.524Z INFO  Fetched group "National Business Expo" with 2 events
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.532Z INFO  Fetched group "Iyania" with 2 events
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.558Z INFO  Fetched group "Cowboy Kim Presents" with 4 events
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.584Z INFO  Group info stored: Motion University
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.587Z INFO  Group info stored: Aduro Film
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.592Z INFO  Group info stored: Iyania
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.594Z INFO  Group info stored: OverlyTurnt
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.596Z INFO  Group info stored: Cowboy Kim Presents
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.598Z INFO  Fetched group "Shuffle HQ" with 2 events
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.600Z INFO  Group info stored: National Business Expo
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.617Z INFO  Fetched group "Ani's Day & Night" with 21 events
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.618Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.618Z INFO  Fetched group "THe Concord" with 25 events
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.619Z INFO  Fetched group "Soniquarium" with 69 events
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.621Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.629Z INFO  Group info stored: Ani's Day & Night
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.640Z INFO  Group info stored: Soniquarium
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.642Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.643Z INFO  Group info stored: THe Concord
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.653Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.665Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.668Z INFO  Group info stored: Shuffle HQ
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.680Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.684Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.705Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.708Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.798Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.950Z INFO  Scraping detailed event: iyanias-24th-birthday-dinner-1
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.968Z INFO  Scraping detailed event: aduro-film-presents-studio-access-pass
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:18.996Z INFO  Scraping detailed event: austin-national-business-expo-1
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.007Z INFO  Scraping detailed event: karaoke-royale-triple-crown-
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.012Z INFO  Scraping detailed event: whs-homecoming-afterparty
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.019Z INFO  Scraping detailed event: atx-tripout-hosted-by-t99zy
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.026Z INFO  Scraping detailed event: iyanias-24th
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.031Z INFO  No search data available, fetching tickets separately for 69cc73af30a8fd53c6c6c96c
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.033Z INFO  No search data available, fetching tickets separately for 69cc18c2b359de6724711864
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.042Z INFO  Scraping detailed event: carnaval-at-anis-day-night
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.068Z INFO  No search data available, fetching tickets separately for 69bee812f005423a7658ca8f
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.077Z INFO  No search data available, fetching tickets separately for 69c2c0690d4a5c53c31e4487
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.080Z INFO  No search data available, fetching tickets separately for 6866be51d95d56220bc09447
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.082Z INFO  Fetched 1 tickets for event 69cc73af30a8fd53c6c6c96c
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.088Z INFO  Fetched 1 tickets for event 69cc18c2b359de6724711864
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.093Z INFO  No search data available, fetching tickets separately for 68eaf64e212bd6a27fe5aa24
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.098Z INFO  Fetched 1 tickets for event 69bee812f005423a7658ca8f
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.109Z INFO  No search data available, fetching tickets separately for 69cc43c2f2cafc542fcc252d
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.117Z INFO  Fetched 2 tickets for event 69c2c0690d4a5c53c31e4487
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.125Z INFO  No search data available, fetching tickets separately for 679ea9d737db2fc95c8b4843
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.131Z INFO  Fetched 2 tickets for event 6866be51d95d56220bc09447
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.138Z INFO  Fetched 2 tickets for event 68eaf64e212bd6a27fe5aa24
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.148Z INFO  Detailed event scraped: Austin National Business Expo
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.149Z INFO  Progress: 1 events scraped
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.152Z INFO  Fetched 1 tickets for event 69cc43c2f2cafc542fcc252d
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.162Z INFO  Detailed event scraped: Aduro Film Presents: Studio Access Pass
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.163Z INFO  Progress: 2 events scraped
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.164Z INFO  Detailed event scraped: ATX TRIPOUT HOSTED BY T99ZY
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.165Z INFO  Progress: 3 events scraped
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.175Z INFO  Fetched 2 tickets for event 679ea9d737db2fc95c8b4843
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.189Z INFO  Detailed event scraped: WHS Homecoming Afterparty
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.190Z INFO  Progress: 4 events scraped
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.195Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.197Z INFO  Detailed event scraped: Iyania’s 24th
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.197Z INFO  Progress: 5 events scraped
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.198Z INFO  Detailed event scraped: KARAOKE ROYALE - Triple Crown 👑🎤
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.199Z INFO  Progress: 6 events scraped
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.200Z INFO  Detailed event scraped: Iyania’s 24th  Birthday Dinner
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.200Z INFO  Progress: 7 events scraped
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.354Z INFO  Detailed event scraped: Carnaval at Ani's Day & Night
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.356Z INFO  Progress: 8 events scraped
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.495Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.510Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.524Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.543Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.551Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.563Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.600Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.602Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.626Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:19.760Z INFO  CheerioCrawler: All requests from the queue have been processed, the crawler will shut down.
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:20.054Z INFO  CheerioCrawler: Final request statistics: {"requestsFinished":28,"requestsFailed":0,"retryHistogram":[28],"requestAvgFailedDurationMillis":null,"requestAvgFinishedDurationMillis":555,"requestsFinishedPerMinute":637,"requestsFailedPerMinute":0,"requestTotalDurationMillis":15527,"requestsTotal":28,"crawlerRuntimeMillis":2636}
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:20.054Z INFO  CheerioCrawler: Finished! Total 28 requests: 28 succeeded, 0 failed. {"terminal":true}
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> 2026-04-01T17:23:20.054Z INFO  Crawler finished. Total events scraped: 8
[apify.posh-vip runId:24JBwdERjQzhl8KQi] -> Status: SUCCEEDED, Message: Starting the crawler.

Processed chunk 10, got 18 results

[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> Status: RUNNING, Message:
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:27.458Z ACTOR: Pulling container image of build VGlEYq35ZQlbL044v from registry.
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:27.460Z ACTOR: Creating container.
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:27.517Z ACTOR: Starting container.
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:27.517Z ACTOR: Running under "LIMITED_PERMISSIONS" permission level.
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:29.485Z INFO  System info {"apifyVersion":"3.5.2","apifyClientVersion":"2.21.0","crawleeVersion":"3.15.3","osType":"Linux","nodeVersion":"v20.19.6"}
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:29.578Z INFO  Starting Posh.vip scraper {"startUrlCount":4,"scrapeEventDetails":true,"maxEvents":2}
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:29.579Z INFO  Detected group page: https://posh.vip/g/hostile-fest
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:29.580Z INFO  Detected group page: https://posh.vip/g/az-vip-1
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:29.580Z INFO  Detected group page: https://posh.vip/g/day-and-night-gallery
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:29.580Z INFO  Detected group page: https://posh.vip/g/pilates-x-mia
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> Status: RUNNING, Message: Starting the crawler.
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:29.835Z INFO  CheerioCrawler: Starting the crawler.
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.356Z INFO  Processing group page: pilates-x-mia
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.356Z INFO  Fetching group data for: pilates-x-mia
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.373Z INFO  Processing group page: az-vip-1
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.374Z INFO  Fetching group data for: az-vip-1
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.378Z INFO  Processing group page: hostile-fest
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.379Z INFO  Fetching group data for: hostile-fest
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.386Z INFO  Processing group page: day-and-night-gallery
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.386Z INFO  Fetching group data for: day-and-night-gallery
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.478Z INFO  Fetched group "HOSTILE FEST" with 1 events
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.483Z INFO  Fetched group "Day and Night Gallery" with 3 events
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.487Z INFO  Fetched group "AZ VIP" with 8 events
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.490Z INFO  Fetched group "Pilates x Mia" with 8 events
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.543Z INFO  Group info stored: HOSTILE FEST
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.549Z INFO  Group info stored: AZ VIP
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.553Z INFO  Group info stored: Day and Night Gallery
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.584Z INFO  Group info stored: Pilates x Mia
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.605Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.613Z INFO  Enqueued 1 events from group for detailed scraping
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.635Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.637Z INFO  Enqueued 2 events from group for detailed scraping
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.866Z INFO  Scraping detailed event: tempe-penthouse-party
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.904Z INFO  Scraping detailed event: gallery-art-opening
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.935Z INFO  Scraping detailed event: galentines-flow-con-amor
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.941Z INFO  Scraping detailed event: beach-blowout-darty
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.942Z INFO  No search data available, fetching tickets separately for 679e5af5a3813764ad7c7db2
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.986Z INFO  Fetched 2 tickets for event 679e5af5a3813764ad7c7db2
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.990Z INFO  No search data available, fetching tickets separately for 67c47a69eef4c6b43c3bdfa8
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:30.996Z INFO  No search data available, fetching tickets separately for 69758c55ba2c7a66cefd0a15
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:31.037Z INFO  Fetched 1 tickets for event 67c47a69eef4c6b43c3bdfa8
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:31.046Z INFO  Fetched 1 tickets for event 69758c55ba2c7a66cefd0a15
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:31.074Z INFO  Detailed event scraped: Tempe Penthouse Party
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:31.074Z INFO  Progress: 1 events scraped
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:31.110Z INFO  Detailed event scraped: Beach Blowout Darty
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:31.110Z INFO  Progress: 2 events scraped
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:31.132Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:31.140Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:31.188Z INFO  Reached max events limit (2). Stopping.
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:31.189Z INFO  Detailed event scraped: Galentine’s Flow Con Amor
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:31.190Z INFO  Progress: 3 events scraped
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:31.966Z INFO  No search data available, fetching tickets separately for 69a4ce8c9a27c94943998027
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:32.001Z INFO  Fetched 1 tickets for event 69a4ce8c9a27c94943998027
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:32.046Z INFO  Detailed event scraped: Gallery Art Opening
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:32.047Z INFO  Progress: 4 events scraped
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:32.129Z INFO  CheerioCrawler: All requests from the queue have been processed, the crawler will shut down.
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:32.339Z INFO  CheerioCrawler: Final request statistics: {"requestsFinished":11,"requestsFailed":0,"retryHistogram":[11],"requestAvgFailedDurationMillis":null,"requestAvgFinishedDurationMillis":579,"requestsFinishedPerMinute":240,"requestsFailedPerMinute":0,"requestTotalDurationMillis":6374,"requestsTotal":11,"crawlerRuntimeMillis":2755}
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:32.340Z INFO  CheerioCrawler: Finished! Total 11 requests: 11 succeeded, 0 failed. {"terminal":true}
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> 2026-04-01T17:23:32.340Z INFO  Crawler finished. Total events scraped: 4
[apify.posh-vip runId:3UwyhK1FyHVJ4MYcX] -> Status: SUCCEEDED, Message: Starting the crawler.

Processed chunk 11, got 8 results
Saved 188 total Posh results as parquet file locally

In [115]:
group_pulls_df[group_pulls_df['type']=='group'].sort_values(by=["totalAttendees"], ascending=False)

,type,groupId,groupUrl,groupName,bio,avatarUrl,contactEmail,website,socials,country,...,activityEnabled,displayOnThirdPartySites,isPaymentPlanEligible,tablesCount,fees,song,youtubeLink,videos,accentColor,lightmode
7,group,65b8ab2753b2972dfae5ea23,https://posh.vip/g/secretsociety,Events by secret society,elevating experiences since 22',https://posh-images-alts-production.s3.amazona...,None,None,{'instagram': 'https://www.instagram.com/secre...,US,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,group,6297bbe528fb980033b2401d,https://posh.vip/g/secretdiscosociety,Secret Disco Society,Secret Disco Society is Austin’s premier under...,https://posh-images-alts-production.s3.amazona...,secretdiscoevents@gmail.com,https://secretdiscosociety.com,{'instagram': 'https://www.instagram.com/secre...,US,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,group,6734641693517bb6a2f3ddbf,https://posh.vip/g/lovemorernb,Love More Rnb,for the rnb lovers,https://posh-images-alts-production.s3.amazona...,info@lovemorernb.com,None,{'instagram': 'https://www.instagram.com/lovem...,US,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,group,6606047e4c657f5dcc91949d,https://posh.vip/g/halfdays,Halfdays,"Hello, we're Halfdays. We're on a mission to b...",https://posh-images-alts-production.s3.amazona...,marketing@halfdays.com,https://www.halfdays.com/,{'instagram': 'https://www.instagram.com/halfd...,US,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,group,656924e03e5f60737b21b04a,https://posh.vip/g/methodthree,M3,We host an array of in-house events to cater t...,https://posh-images-alts-production.s3.amazona...,Roxy@methodthree.com,https://methodthree.com/,{'instagram': 'https://www.instagram.com/m3atx'},US,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,group,68807e9e9b513722283dbfc3,https://posh.vip/g/themove-atx,The Move,Community | VIBES x FOMO,https://posh-images-alts-production.s3.amazona...,None,None,{'instagram': 'https://www.instagram.com/sipea...,US,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,group,68914e52ea8e48ff8b0b7038,https://posh.vip/g/sonus-productions,Sonus Productions,Sonus Productions is a cutting-edge event prod...,https://posh-images-alts-production.s3.amazona...,onket_industries@outlook.com,https://sonusproductions.net,{'instagram': 'https://www.instagram.com/sonus...,US,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,group,69ac58ddec1e269e4d97bd38,https://posh.vip/g/ruffhouse-collective,Ruffhouse Collective,None,https://posh-images-alts-production.s3.amazona...,ruffhouse512@gmail.com,None,{},US,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,group,65963a60aa3436a647f480e5,https://posh.vip/g/atxsupperclub,ATX Supper Club,ATX SUPPER CLUB WAS CREATED OUT OF A LOVE FOR ...,https://images.posh.vip/images/7a49cc50-3976-4...,hello@atxsupperclub.com,https://atxsupperclub.com/,{'instagram': 'https://www.instagram.com/atx.s...,US,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,group,69cc3aefb0c4585d8983189f,https://posh.vip/g/craftery-tx,Craftery TX,"Crafts for Community in Austin & Lakeway, TX!",https://posh-images-originals-production.s3.am...,crafterylakeway@gmail.com,https://crafterytx.com,{'instagram': 'https://www.instagram.com/craft...,US,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
small_mala_vida_result

[{'type': 'group',
  'groupId': '68e16fc6cf45d1389f698c2c',
  'groupUrl': 'https://posh.vip/g/malavida',
  'groupName': 'MALA VIDA',
  'bio': 'Mala Vida is a premier Latin nightclub located in the heart of Austin. Known for its vibrant energy, top-tier DJs, and unforgettable parties, Mala Vida specializes in creating exclusive VIP experiences that bring the best of Latin nightlife to Sixth Street. From bottle service to high-energy reggaetón nights, Mala Vida sets the standard for Austin’s Latin club scene.',
  'avatarUrl': 'https://posh-images-alts-production.s3.amazonaws.com/68e33b38a22c00402622e879/600x600.png',
  'contactEmail': None,
  'website': None,
  'socials': {'instagram': 'https://www.instagram.com/malavidaaustin'},
  'country': 'US',
  'currency': 'USD',
  'verified': False,
  'totalAttendees': 4458,
  'totalEvents': 31,
  'createdAt': '2025-10-04T19:04:42.018Z',
  'scrapedAt': '2026-04-01T16:42:28.373Z',
  'source': 'posh_vip'},
 {'eventId': '68e3057a747bf3df1659de7a',
  'eventUrl': 'https://posh.vip/e/perreo-2000-y2k-reggaeton-1',
  'eventTitle': 'Perreo 2000 Y2k Reggaeton Houston',
  'description': '**Y2K Perreo 2000 Party – Viernes, Oct 10 @ Mala Vida Houston** 🎶\\\nBack to the OG reggaetón vibes : *Gasolina, Rakata, Lo Que Pasó Pasó* y más.\\\nPerreo intenso toda la noche.\n\n📍 1201 St Emanuel St #110, Houston, TX 77003',
  'shortDescription': 'Y2K Perreo 2000 Party - Fri Oct 10 at Mala Vida Houston! Reggaeton classics all night. VIP tables avail. 📍1201 St Emanuel St #110, Houston',
  'coverUrl': 'https://posh-images-originals-production.s3.amazonaws.com/68e3082b24c1a6f96d24dd2f',
  'startDateTime': '2025-10-11T02:00:00.000Z',
  'endDateTime': '2025-10-11T07:00:00.000Z',
  'timezone': 'America/Chicago',
  'status': 'live',
  'isRSVPEvent': True,
  'isLive': True,
  'venue': {'name': 'Mala Vida Houston',
   'address': '1201 St Emanuel St #110',
   'city': 'Houston',
   'stateCode': 'TX',
   'zipCode': '77003',
   'coordinates': None},
  'venueName': 'Mala Vida Houston',
  'address': '1201 St Emanuel St #110',
  'city': 'Houston',
  'stateCode': 'TX',
  'zipCode': '77003',
  'organizer': {'id': '68e16fc6cf45d1389f698c2c',
   'name': 'MALA VIDA',
   'email': None,
   'logo': 'https://posh-images-alts-production.s3.amazonaws.com/68e33b38a22c00402622e879/600x600.png',
   'url': 'https://posh.vip/malavida',
   'verified': False,
   'currency': 'USD',
   'country': 'US',
   'socials': {'instagram': 'https://www.instagram.com/malavidaaustin'}},
  'organizerName': 'MALA VIDA',
  'organizerId': '68e16fc6cf45d1389f698c2c',
  'performers': [],
  'lineup': [],
  'performanceCategory': 'Event Features',
  'tickets': [{'id': '68e3057a747bf3df1659de7c',
    'name': 'FREE WITH RSVP',
    'price': 0,
    'totalPrice': 0,
    'quantityAvailable': 15,
    'description': '🎟️ **Y2K Perreo 2000 Party**\nYour all-access pass to the ultimate reggaetón throwback at Mala Vida, **Friday, October 10th**.\n\n✨ _FREE with RSVP_ – skip the line, secure your spot, and dance all night to the classics — Gasolina, Rakata, Lo Que Pasó Pasó y más.\n\n📍 **Mala Vida – 1201 Saint Emanuel St, Suite 110, Houston, TX 77003**',
    'isAvailable': False,
    'isHidden': False,
    'isFree': True,
    'approvalRequired': False,
    'isTransferable': False,
    'purchaseLimit': None,
    'onSale': None,
    'endSale': None,
    'waitlistEnabled': False}],
  'ticketGroups': [],
  'lowestPrice': None,
  'highestPrice': None,
  'isFreeEvent': True,
  'hasPasswordProtectedTickets': False,
  'attendingCount': 1,
  'guestlistEnabled': True,
  'activityEnabled': False,
  'displayOnThirdPartySites': True,
  'isPaymentPlanEligible': False,
  'tablesCount': 0,
  'fees': [],
  'song': {'name': 'Rakata', 'artist': 'Wisin & Yandel'},
  'youtubeLink': None,
  'videos': [],
  'accentColor': '#1c832c',
  'lightmode': False,
  'scrapedAt': '2026-04-01T16:42:28.994Z',
  'source': 'posh_vip'}]

In [82]:
pd.DataFrame(mala_vida_results)

,type,groupId,groupUrl,groupName,bio,avatarUrl,contactEmail,website,socials,country,...,activityEnabled,displayOnThirdPartySites,isPaymentPlanEligible,tablesCount,fees,song,youtubeLink,videos,accentColor,lightmode
0,group,68e16fc6cf45d1389f698c2c,https://posh.vip/g/malavida,MALA VIDA,Mala Vida is a premier Latin nightclub located...,https://posh-images-alts-production.s3.amazona...,NaN,NaN,{'instagram': 'https://www.instagram.com/malav...,US,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],"{'name': 'Rakata', 'artist': 'Wisin & Yandel'}",NaN,[],#2ce6ea,False
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],"{'name': 'Gasolina', 'artist': 'Daddy Yankee'}",NaN,[],#661e1f,False
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],None,NaN,[],#99047e,False
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],None,NaN,[],#985978,False
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],"{'name': 'Yandel 150', 'artist': 'Yandel'}",NaN,[],#2e5c91,False
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],"{'name': 'Chambea', 'artist': 'Bad Bunny'}",NaN,[],#cc3c3c,False
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],"{'name': 'Yeah! (feat. Lil Jon & Ludacris)', '...",NaN,[],#9e1c4c,False
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],"{'name': 'Passionfruit', 'artist': 'Drake'}",NaN,[],#94541c,False
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],"{'name': 'Rakata', 'artist': 'Wisin & Yandel'}",NaN,[],#1c832c,False
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],None,NaN,[],#985978,False
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],"{'name': 'LA CANCIÓN', 'artist': 'J Balvin'}",NaN,[],#29cc64,False
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],"{'name': 'LA CANCIÓN', 'artist': 'J Balvin'}",NaN,[],#29cc64,False
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],"{'name': 'Rakata', 'artist': 'Wisin & Yandel'}",NaN,[],#6ae6f0,False
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],"{'name': 'Jamaican (Bam Bam)', 'artist': 'HUGEL'}",NaN,[],#d86117,False
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],None,NaN,[],#ce0606,False
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],"{'name': 'Tití Me Preguntó', 'artist': 'Bad Bu...",NaN,[],#7f7f7f,False
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],"{'name': 'Famous', 'artist': 'Kanye West'}",NaN,[],#7f7f7f,False
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],"{'name': 'Jamaican (Bam Bam)', 'artist': 'HUGEL'}",NaN,[],#d86117,False
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],"{'name': '2/Catorce', 'artist': 'Rauw Alejandro'}",NaN,[],#7f7f7f,False
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],"{'name': 'Rakata', 'artist': 'Wisin & Yandel'}",NaN,[],#6ae6f0,False
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],"{'name': 'Die With A Smile', 'artist': 'Lady G...",NaN,[],#7f7f7f,False
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],"{'name': 'Rakata', 'artist': 'Wisin & Yandel'}",NaN,[],#7f7f7f,False
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],"{'name': 'Just Dance', 'artist': 'Lady Gaga'}",NaN,[],#7f7f7f,False
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],None,NaN,[],#7f7f7f,False
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],"{'name': 'Bodak Yellow', 'artist': 'Cardi B'}",NaN,[],#7f7f7f,False
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],"{'name': 'Cuando No Era Cantante - Remix', 'ar...",NaN,[],#9c24e4,False
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],"{'name': 'DtMF', 'artist': 'Bad Bunny'}",NaN,[],#3a5b63,False
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],"{'name': 'ALAKRAN', 'artist': 'Feid'}",NaN,[],#14a444,False
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],"{'name': 'Atrévete-Te-Te', 'artist': 'Calle 13'}",NaN,[],#14a444,False
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],"{'name': 'dopamina', 'artist': 'Peso Pluma'}",NaN,[],#7f7f7f,False
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,0.0,[],"{'name': 'Baby', 'artist': 'Justin Bieber'}",NaN,[],#7f7f7f,False

In [116]:
#using skip trace apify api 

from crawler import APIFY_TOKEN



def fetch_luma(input_params: dict) -> list[dict]:
    """
    For each name, phone number, or email, fetch associated Instagram accounts using Skip Trace API.
    At least one of name, phone_number, or email must be provided.
    """
    # if not (input_params.get("name") or input_params.get("phone_number") or input_params.get("email")):
    #     raise ValueError("At least one of name, phone_number, or email must be provided.")
    
    LUMA_TRACE = 'matyascimbulka/luma-event-scraper'
    apify = ApifyClient(APIFY_TOKEN)

    run = apify.actor(LUMA_TRACE).call(run_input=input_params)
    return list(apify.dataset(run["defaultDatasetId"]).iterate_items())

In [ ]:
luma_input = {
  "slugs": [
    "ai",
    "tech"
  ],
  "cities": [
    "Austin"
  ]
}